print("  _")
print(" ) )")
print("( ( .-''''-.  A.-.A")
print("\ \/        \/ , , \ ")
print(" \   \      =;  t  /=")
print("  \  |''''.   ',--'")
print("  / //     | | |")
print(" /_,))     |_,))")