# -*- coding: utf-8 -*-
"""AnnualPipeBurst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvAJhvwk50PfMKIGwgjaCgIxNd38_ox-
"""

# prompt: write a python script that will import python docx and uses it to make documents that follow the same format but with filled in blanks that I will specify. The program should prompt the user, asking them to answer questions which will fill in the blanks of the document.

!pip install python-docx

from docx import Document
#str template_path = "C:\Users\Masset.Ethan\OneDrive - WESTON & SAMPSON ENGINEERS, Inc\Desktop\Point Repair\SS7619_XXXXXMH_XXXXXMH_1234AbcSt_PR_2025MMDD.docx";
#str output_path = "C:\Users\Masset.Ethan\OneDrive - WESTON & SAMPSON ENGINEERS, Inc\Desktop\Point Repair";
def create_document_from_template(template_path, output_path, replacements):
  """
  Creates a new document based on a template, filling in specified blanks.

  Args:
    template_path (str): The path to the template .docx file.
    output_path (str): The path to save the new .docx file.
    replacements (dict): A dictionary where keys are the placeholders in the
                         template (e.g., "[NAME]") and values are the
                         corresponding text to insert.
  """
  try:
    document = Document(template_path)

    for paragraph in document.paragraphs:
      for key, value in replacements.items():
        if key in paragraph.text:
          inline = paragraph.runs
          # Replace the placeholder while preserving formatting
          for i in range(len(inline)):
            if key in inline[i].text:
              text = inline[i].text.replace(key, value)
              inline[i].text = text

    document.save(output_path)
    print(f"Document saved successfully to {output_path}")

  except FileNotFoundError:
    print(f"Error: Template file not found at {template_path}")
  except Exception as e:
    print(f"An error occurred: {e}")

if __name__ == "__main__":
  # --- User Input ---
  # Define the path to your template document
  # Upload your template.docx file to Colab's environment first.
  # You can do this by clicking the folder icon on the left sidebar, then the upload icon.
  # After uploading, right-click on the file in the file browser and select "Copy path".
  template_doc_path = r"/content/SS7619_XXXXXMH_XXXXXMH_1234AbcSt_PR_2025MMDD.docx" # Paste the copied path here

  # Define the placeholders in your template and the questions to ask the user
  questions = {
      "[DATE]": "What is the date of the visit? ",
      "[TIME]": "What is the time of the visit? ",
      "[WEATHER]": "What is the weather? (ex. 78 Sunny) ",
      "[ADDY]": "What is the address of the repair? ",
      "[LENGTHREP]": "What is the feet of length is the repair? ",
      "[TYPEPIPE]": "Is this a lateral or a main line point repair? ",
      "[MH1]": "What is the first manhole name? ",
      "[MH2]": "What is the second manhole name? ",
      "[CONTR]": "What is the Contractor's name? ",
      "[FTAWAY]": "How many feet away from manhole 1 was the repair? ",
      "[REASON]": "What is the reason for the repair? ",
      "[FTUNDER]": "How many feet below the surface is the pipe? ",
      "[NEWDIA]": "What is the diameter of the new pipe? ",
      "[NEWTYPE]": "What is the type of the new pipe? ",
      "[AMTSERVICE]": "How many services are being reconnected? ",
      "[ANDPERFORMEDUSING]": "What materials were used to reconnect the services?(format: and performed using *listofmaterials*) ",
      "[PARENTORFLOW]": "Did they backfill with parent material or flow fill and asphalt? ",
      "[AMTFLOW]": "How many yards of flow fill? ",
      "[AMTASPH]": "How many sq yards of asphalt? ",
      "[OTHEREQUIP]": "Other than a mini ex, what equipment was on site? ",


      # Add more placeholders and questions as needed
  }
  MH1 = input("What is the first manhole name? ")
  MH2 = input("What is the second manhole name? ")
  ADDY = input("What is the address of the repair? ")
  DATE = input("What is the date of the visit? ")

  # Collect user input
  user_responses = {}
  print("Please provide the following information to fill in the document:")
  for placeholder, question in questions.items():
    answer = input(question)
    user_responses[placeholder] = answer

  # --- Document Creation ---
  output_doc_path = 'SS7619_'+MH1+'_'+MH2+'_'+ADDY+'_PR_'+DATE+'.docx' # Define the output file name

  create_document_from_template(template_doc_path, output_doc_path, user_responses)

  # You can then download the file if you are in Colab
  try:
    from google.colab import files
    files.download(output_doc_path)
  except ImportError:
    print("Not in Google Colab environment. File saved locally.")

# Example of a simple template.docx content:
# Dear [NAME],
#
# This letter is to confirm your start date with [COMPANY] on [DATE].
#
# Sincerely,
# [YOUR NAME] (replace manually or add another placeholder)