{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a55aa3d7-6986-4c5a-8bc7-38c42961e6e1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b47b3810-5358-48d9-9a0f-3b8078381a26",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "\n",
    "class AntiCorruptionCultureTest:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Тест: Роль массовой культуры в противодействии коррупции\")\n",
    "        self.root.geometry(\"600x400\")\n",
    "\n",
    "        self.questions = [\n",
    "            {\n",
    "                \"text\": \"В массовой культуре появляются фильмы и сериалы, раскрывающие коррупционные схемы и последствия коррупции. Какой эффект это может оказать на общество?\",\n",
    "                \"options\": {\n",
    "                    \"а\": \"Публика станет пассивной, так как видит коррупцию как неизбежное зло.\",\n",
    "                    \"б\": \"Фильмы пробуждают общественный резонанс, повышают осознанность и стимулируют требовать перемен.\",\n",
    "                    \"в\": \"Массовая культура просто развлекает, и на реальное отношение к коррупции не влияет.\"\n",
    "                },\n",
    "                \"comments\": {\n",
    "                    \"а\": \"Это неверно — правильные истории мотивируют бороться, а не смиряться.\",\n",
    "                    \"б\": \"Верно! Образовательные и остросоциальные сюжеты помогают формировать негативное отношение к коррупции.\",\n",
    "                    \"в\": \"Недооценка силы массовой культуры — она способна формировать ценности и взгляды.\"\n",
    "                },\n",
    "                \"correct\": \"б\"\n",
    "            },\n",
    "            {\n",
    "                \"text\": \"Музыка и песни иногда затрагивают тему коррупции и социальной справедливости. Какую роль они играют в борьбе с коррупцией?\",\n",
    "                \"options\": {\n",
    "                    \"а\": \"Помогают донести идеи честности и справедливости до широкой аудитории, вдохновляют на действия.\",\n",
    "                    \"б\": \"Музыка — это просто развлечение и не влияет на серьёзные социальные проблемы.\",\n",
    "                    \"в\": \"Такую музыку слушают только узкие группы, и она не влияет на массовое сознание.\"\n",
    "                },\n",
    "                \"comments\": {\n",
    "                    \"а\": \"Точно! Музыка — мощный инструмент социальной коммуникации и мотивации.\",\n",
    "                    \"б\": \"Это заблуждение: искусство часто меняет общественное мнение и вдохновляет на перемены.\",\n",
    "                    \"в\": \"Многие хиты достигают миллионов слушателей и формируют общественные настроения.\"\n",
    "                },\n",
    "                \"correct\": \"а\"\n",
    "            },\n",
    "            {\n",
    "                \"text\": \"Как могут социальные сети и блогеры влиять на восприятие коррупции в обществе?\",\n",
    "                \"options\": {\n",
    "                    \"а\": \"Распространять информацию, разоблачать коррупционные схемы и поддерживать активистов.\",\n",
    "                    \"б\": \"Создавать хаос и ложные обвинения без доказательств, что снижает доверие к борьбе с коррупцией.\",\n",
    "                    \"в\": \"Быть площадкой только для обсуждения мемов и развлечений, не затрагивая серьёзные темы.\"\n",
    "                },\n",
    "                \"comments\": {\n",
    "                    \"а\": \"Правильно! Социальные медиа — инструмент прозрачности и давления на власти.\",\n",
    "                    \"б\": \"Хотя такое бывает, важно поддерживать ответственность и проверку информации.\",\n",
    "                    \"в\": \"Социальные сети могут быть чем угодно, но активно используемые для борьбы с коррупцией — сильный ресурс.\"\n",
    "                },\n",
    "                \"correct\": \"а\"\n",
    "            }\n",
    "        ]\n",
    "\n",
    "        self.current_question = 0\n",
    "        self.score = 0\n",
    "\n",
    "        self.progress_label = tk.Label(root, text=\"\", font=(\"Arial\", 12))\n",
    "        self.progress_label.pack(pady=5)\n",
    "\n",
    "        self.question_label = tk.Label(root, text=\"\", wraplength=580, font=(\"Arial\", 14), justify=\"left\")\n",
    "        self.question_label.pack(pady=10)\n",
    "\n",
    "        self.var = tk.StringVar()\n",
    "\n",
    "        self.radio_buttons = []\n",
    "        for option in [\"а\", \"б\", \"в\"]:\n",
    "            rb = tk.Radiobutton(root, text=\"\", variable=self.var, value=option, font=(\"Arial\", 12), wraplength=580, justify=\"left\")\n",
    "            rb.pack(anchor=\"w\", padx=20, pady=5)\n",
    "            self.radio_buttons.append(rb)\n",
    "\n",
    "        self.next_button = tk.Button(root, text=\"Ответить\", command=self.next_question)\n",
    "        self.next_button.pack(pady=20)\n",
    "\n",
    "        self.feedback_label = tk.Label(root, text=\"\", fg=\"blue\", font=(\"Arial\", 12), wraplength=580, justify=\"left\")\n",
    "        self.feedback_label.pack(pady=10)\n",
    "\n",
    "        self.show_question()\n",
    "\n",
    "    def show_question(self):\n",
    "        q = self.questions[self.current_question]\n",
    "        self.progress_label.config(text=f\"Вопрос {self.current_question + 1} из {len(self.questions)}\")\n",
    "        self.question_label.config(text=q[\"text\"])\n",
    "        self.var.set(\"\")  # исправлено здесь\n",
    "        self.feedback_label.config(text=\"\")\n",
    "        for i, option in enumerate([\"а\", \"б\", \"в\"]):\n",
    "            self.radio_buttons[i].config(text=f\"{option}) {q['options'][option]}\")\n",
    "\n",
    "    def next_question(self):\n",
    "        choice = self.var.get()\n",
    "        if choice not in [\"а\", \"б\", \"в\"]:\n",
    "            messagebox.showwarning(\"Внимание\", \"Пожалуйста, выберите один из вариантов ответа.\")\n",
    "            return\n",
    "\n",
    "        q = self.questions[self.current_question]\n",
    "        if choice == q[\"correct\"]:\n",
    "            self.score += 1\n",
    "\n",
    "        comment = q[\"comments\"][choice]\n",
    "        self.feedback_label.config(text=comment)\n",
    "\n",
    "        self.next_button.config(state=\"disabled\")\n",
    "        self.root.after(3000, self.next_step)  # Показываем комментарий 3 секунды\n",
    "\n",
    "    def next_step(self):\n",
    "        self.current_question += 1\n",
    "        if self.current_question >= len(self.questions):\n",
    "            self.show_final_score()\n",
    "        else:\n",
    "            self.show_question()\n",
    "            self.next_button.config(state=\"normal\")\n",
    "            self.feedback_label.config(text=\"\")\n",
    "\n",
    "    def show_final_score(self):\n",
    "        total = len(self.questions)\n",
    "        if self.score == total:\n",
    "            message = \"Вы отлично разбираетесь в теме! Массовая культура в ваших руках — мощное оружие против коррупции!\"\n",
    "        elif self.score == total - 1:\n",
    "            message = \"Хороший результат! Вы видите, как массовая культура может влиять на общественные ценности.\"\n",
    "        elif self.score == 1:\n",
    "            message = \"Неплохо, но стоит глубже задуматься о роли культуры в борьбе с коррупцией.\"\n",
    "        else:\n",
    "            message = \"Похоже, вы недооцениваете влияние культуры. Рекомендуем посмотреть актуальные фильмы, послушать социальную музыку и следить за блогерами-активистами.\"\n",
    "\n",
    "        messagebox.showinfo(\"Результат теста\", f\"Ваш результат: {self.score} из {total}\\n\\n{message}\")\n",
    "        self.root.quit()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = AntiCorruptionCultureTest(root)\n",
    "    root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e7fe497-fc56-4d5f-acac-da0ed517af3d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d6a2982-8fab-4117-a747-5be7c7e06619",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aef0ac13-ff0a-4385-878a-be6b7b6a24f7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e567dc99-e35b-481c-90a9-aa9c8efa68f2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
