print("Python is fun!")
print("Burgers")
print("Green")
print("I like to play VR")
print("She said, \'Python is cool!\'")
print("Cheetah")
print("\n \tVR")
print("    /\\")
print("   /  \\")
print("  /    \\")
print(" /      \\")
print("/        \\")
print("----------")
print("#########")
print("*       *")
print("*       *")
print("*  YOU  *")
print("*  ARE  *")
print("* LOVED *")
print("* ^   ^ *")
print("* \___/ *")
print("#########")