import tkinter as tk
import sys
import os

print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")
print("lol")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("kokote!!!!")
print("0 cool")
print("lol")
print("kokote!!!!")
print("0 cool")
print("cok.py")
print("1,0000 kokoty")


def create_ransomware_prank():
    root = tk.Tk()
    root.title("hraj s")
    
    # Nastavení okna tak, aby bylo vždy nahoře a nešlo snadno zavřít
    root.attributes("-topmost", True)
    root.overrideredirect(True) # Odstraní standardní rámeček okna (tlačítka zavřít/minimalizovat)
    root.geometry("800x400+{}+{}".format(root.winfo_screenwidth() // 2 - 400, root.winfo_screenheight() // 2 - 200)) # Centruje okno

    # Zakázání změn velikosti
    root.resizable(False, False)

    # Červená barva pozadí pro dojem naléhavosti
    root.configure(bg="darkred")

    # Text zprávy
    message = (
        "VAŠE SOUBORY BYLY ZAMKNUTY!\n\n"
        "Nepokoušejte se vypnout počítač nebo program ukončit. "
        "Veškerá vaše data jsou zašifrována. "
        "Pro obnovení dat prosím následujte instrukce na:\n\n"
        " https://www.youtube.com/@Jakub391\n \n"
        "Máte 10 minut na odbrerat, jinak budou soubory PERMANENTNĚ smazány.\n\n"
        "Pro ukončení žertu stiskněte klávesu 'Q'."
    )
    
    label = tk.Label(
        root,
        text=message,
        fg="white", # Barva textu
        bg="darkred", # Barva pozadí textu
        font=("Consolas", 18, "bold"), # Font a velikost
        justify=tk.CENTER,
        wraplength=700 # Zalamování textu
    )
    label.pack(expand=True, fill="both", padx=20, pady=50)

    def close_prank(event=None):
        """
        Funkce pro ukončení žertu. 
        Může být volána stiskem klávesy 'q' nebo po uplynutí času.
        """
        root.destroy()
        sys.exit()

    # Automatické ukončení po 30 sekundách (pro případ, že uživatel nenajde 'Q')
    root.after(30000, close_prank) # 30000 ms = 30 sekund

    # Umožní ukončení žertu stiskem klávesy 'q' (case-insensitive)
    root.bind("<KeyPress-q>", close_prank)
    root.bind("<KeyPress-Q>", close_prank)

    root.mainloop()

if __name__ == "__main__":
    create_ransomware_prank()


