# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz. adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DNA41hDlkbeWVm0OvwNHMazQvKPdAsE
"""

KgFiyatUSD = float(input('KG/USD fiyatı girin: '))
KgFiyatEUR = KgFiyatUSD/1.18
ComissionRate = float(input('Komisyon oranını girin : '))
width = int((input('Width girin (cm): ')))
gram = int(input('gramaj girin (g) : '))
KgBaşınaDüşenMt = 100000/(width*gram)
MtFiyatEUR = KgFiyatEUR/KgBaşınaDüşenMt + 0.30 + (KgFiyatEUR/KgBaşınaDüşenMt)*ComissionRate
print(MtFiyatEUR  , 'EUR/MT CONVENTIONAL CIF TRUCK PRICE')
print('NOT: Güncel Parite 1,18')