# -*- coding: utf-8 -*-
"""Copy of RAPORT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLlIlQgNRcsMBJBc1mr_zJ_72xksOLFh
"""

import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime

# Setup Google Sheets API
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive"
]
creds = ServiceAccountCredentials.from_json_keyfile_name("service_account.json", scope)
client = gspread.authorize(creds)
sheet_id = "1abcdefghijklmnopqrstuvwxyz12345678"  # UBAH ke ID Anda

# Sheet untuk nilai siswa
sheet_nilai = client.open_by_key(sheet_id).worksheet("Nilai")   # Worksheet "Nilai"
# Sheet untuk absensi siswa
sheet_absensi = client.open_by_key(sheet_id).worksheet("Absensi")  # Worksheet "Absensi"
# Sheet untuk workflow/log
sheet_log = client.open_by_key(sheet_id).worksheet("WorkflowLog")  # Worksheet "WorkflowLog"

# Fungsi catat nilai siswa
def catat_nilai(nama, kelas, mapel, nilai):
    waktu = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # Header sekali waktu, jika sheet kosong
    if not sheet_nilai.get_all_values():
        sheet_nilai.append_row(["Waktu Input", "Nama", "Kelas", "Mata Pelajaran", "Nilai"])
    sheet_nilai.append_row([waktu, nama, kelas, mapel, nilai])
    print(f"Nilai {nama} tercatat di Google Sheets.")

# Fungsi catat absensi siswa
def catat_absensi(nama, kelas, status):
    waktu = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    if not sheet_absensi.get_all_values():
        sheet_absensi.append_row(["Tanggal", "Nama", "Kelas", "Status"])
    sheet_absensi.append_row([waktu, nama, kelas, status])
    print(f"Absensi {nama} tercatat di Google Sheets.")

# Fungsi log workflow
def catat_log(workflow_id, aktivitas, status):
    waktu = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    if not sheet_log.get_all_values():
        sheet_log.append_row(["WorkflowID", "Waktu", "Aktivitas", "Status"])
    sheet_log.append_row([workflow_id, waktu, aktivitas, status])
    print("Workflow tercatat di Google Sheets.")

# ==== Contoh penggunaan manual ====
# Catat nilai
catat_nilai("Ali", "10 IPA 1", "Matematika", 88)

# Catat absensi
catat_absensi("Ali", "10 IPA 1", "Hadir")

# Catat log workflow
catat_log("17097525713", "Input Nilai Matematika", "SUKSES")