import os
import time

print("Установка 1%")
time.sleep(5)
os.system('cls')
print("Установка 9%")
time.sleep(4)
os.system('cls')
print("Установка 25%")
time.sleep(12)
os.system('cls')
print("Установка 51%")
time.sleep(6)
os.system('cls')
print("Установка 97%")
time.sleep(1)
os.system('cls')
print("Установка 99%")
time.sleep(10)
os.system('cls')
print("Завершено!")
time.sleep(3)
exit()
