from Tkinter import *
import openpyxl
import pandas
fenetre=Tk()
obj=LabelFrame(fenetre,text="Prof",font=20,bd=2,width=500,height=160,relief=GROOVE)
obj.place(x=20,y=20)
titre=Label(fenetre, text="Nom et Pr�nom",font='bold')
titre.place(x=40,y=50)
entre1=Entry(fenetre, bg="yellow", width=30,font='bold')
entre1.place(x=200,y=50)
titre=Label(fenetre, text="Sp�cialit�",font='bold')
titre.place(x=40,y=70)
entre2=Entry(fenetre, bg="yellow", width=30,font='bold')
entre2.place(x=200,y=70)
titre=Label(fenetre, text="T�l",font='bold')
titre.place(x=40,y=90)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=90)

obj=LabelFrame(fenetre,text="El�ve",font=20,bd=2,width=500,height=300,relief=GROOVE)
obj.place(x=20,y=280)

titre=Label(fenetre, text="Nom et Pr�nom",font='bold')
titre.place(x=40,y=320)
entre1=Entry(fenetre, bg="yellow", width=30,font='bold')
entre1.place(x=200,y=320)
titre=Label(fenetre, text="Niveau",font='bold')
titre.place(x=40,y=340)
entre2=Entry(fenetre, bg="yellow", width=30,font='bold')
entre2.place(x=200,y=340)
titre=Label(fenetre, text="T�l",font='bold')
titre.place(x=40,y=360)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=360)
titre=Label(fenetre, text="Mati�re",font='bold')
titre.place(x=40,y=380)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=380)
titre=Label(fenetre, text="Date Inscription",font='bold')
titre.place(x=40,y=400)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=400)
titre=Label(fenetre, text="Prix",font='bold')
titre.place(x=40,y=420)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=420)
titre=Label(fenetre, text="Avance",font='bold')
titre.place(x=40,y=440)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=440)
titre=Label(fenetre, text="Reste",font='bold')
titre.place(x=40,y=460)
entre3=Entry(fenetre, bg="yellow", width=30,font='bold')
entre3.place(x=200,y=460)
def calculer():  
                  classeur = openpyxl.load_workbook('test.xlsx')
                  feuille = classeur.active
                  derniere_ligne = feuille.max_row
                  nouvelle_ligne_index = derniere_ligne + 1
                  feuille.cell(row=nouvelle_ligne_index, column=1, value=entre1.get())
                  feuille.cell(row=nouvelle_ligne_index, column=2, value=entre2.get())
                  feuille.cell(row=nouvelle_ligne_index, column=3, value=entre3.get())
                  #feuille['A2'] = entre1.get()
                  #feuille['B2'] = entre2.get()
                  #feuille['C2'] = entre3.get()
                  classeur.save("test.xlsx")
                 
                
bouton= Button(fenetre, text="Enregistrer",bg="black",fg="white", command = calculer,font='bold' )
bouton.place(x=200,y=120)
bouton= Button(fenetre, text="Afficher liste",bg="black",fg="white", command = calculer,font='bold')
bouton.place(x=300,y=120)
bouton= Button(fenetre, text="Enregistrer",bg="black",fg="white", command = calculer,font='bold')
bouton.place(x=160,y=500)
bouton= Button(fenetre, text="Afficher liste",bg="black",fg="white", command = calculer,font='bold')
bouton.place(x=260,y=500)
bouton= Button(fenetre, text="Re�u",bg="black",fg="white", command = calculer,font='bold')
bouton.place(x=370,y=500)


fenetre.title("LEARN ZONE")
fenetre.configure(bg="GREEN")
fenetre.minsize(700,600)
fenetre.mainloop()
