# -*- coding: utf-8 -*-
"""kondensat hesabı.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPZg7P0Xs8miiFxaJ9ZTXMtjg-gvcQN4
"""

import numpy as np
import math

# Fonksiyonlar
def dew_point(T, RH):
    a = 17.27
    b = 237.7
    alpha = ((a * T) / (b + T)) + np.log(RH/100.0)
    Td = (b * alpha) / (a - alpha)
    return Td

def min_insulation_thickness(Ta, Tm, Td, h, lambda_):
    if (Td - Tm) <= 0:
        return 0.0
    d = (lambda_ / h) * ( (Ta - Tm)/(Td - Tm) - 1 )
    return max(d, 0.0)

def ampirik_izolasyon_kalinligi(T_boru):
    if T_boru > 10:
        return 0
    elif T_boru > 0:
        return 25
    elif T_boru > -10:
        return 35
    elif T_boru > -25:
        return 45
    elif T_boru > -40:
        return 55
    else:
        return 65

def heat_loss(Tm, Ta, lambda_, r1, r2):
    Q = (2 * math.pi * lambda_ * (Tm - Ta)) / math.log(r2/r1)
    return Q

# Kullanıcıdan veri alma
print("--- IsoCalc 5.0 Benzeri İzolasyon Hesaplama ---")
print("Tüm parametreleri giriniz:")
project = input("Proje adı: ")
company = input("Şirket adı: ")
date = input("Tarih: ")
material = input("İzolasyon malzemesi: ")
Ta = float(input("Ortam sıcaklığı (°C): "))
Tm = float(input("Boru/medium sıcaklığı (°C): "))
RH = float(input("Bağıl nem (%): "))
h = float(input("Yüzey ısı transfer katsayısı (W/m²K): "))
lambda_ = float(input("Isı iletim katsayısı (W/mK): "))
sales_contact = input("Satış irtibatı: ")

# Boru çapı ve izolasyon kalınlığı (ısı kaybı hesabı için opsiyonel)
boru_capi = float(input("Boru çapı (mm): ")) / 1000  # mm'yi m'ye çevir
izolasyon_kalinligi = float(input("Isı kaybı hesabı için izolasyon kalınlığı (mm): ")) / 1000  # mm'yi m'ye çevir

# Hesaplamalar
Td = dew_point(Ta, RH)
d = min_insulation_thickness(Ta, Tm, Td, h, lambda_)
d_ampirik = ampirik_izolasyon_kalinligi(Tm)
r1 = boru_capi / 2
r2 = r1 + izolasyon_kalinligi
Q = heat_loss(Tm, Ta, lambda_, r1, r2)

# Sonuçları yazdırma
print("\n--- Hesaplama Sonuçları ---")
print(f"Proje: {project}")
print(f"Şirket: {company}")
print(f"Tarih: {date}")
print(f"İzolasyon malzemesi: {material}")
print(f"Ortam sıcaklığı: {Ta} °C")
print(f"Boru/medium sıcaklığı: {Tm} °C")
print(f"Bağıl nem: {RH} %")
print(f"Yüzey ısı transfer katsayısı: {h} W/m²K")
print(f"Isı iletim katsayısı: {lambda_} W/mK")
print(f"Çiğ noktası sıcaklığı: {Td:.2f} °C")
print(f"Minimum izolasyon kalınlığı (ISO 12241:1998): {d*1000:.2f} mm")
print(f"Nominal kalınlık önerisi (pratik): {max(6, round(d*1000))} mm")
print(f"Ampirik (pratik) izolasyon kalınlığı önerisi: {d_ampirik} mm")
print(f"Satış irtibatı: {sales_contact}")
print(f"\nIsı kaybı hesabı (verilen izolasyon kalınlığı için):")
print(f"Boru çapı: {boru_capi*1000:.1f} mm")
print(f"İzolasyon kalınlığı: {izolasyon_kalinligi*1000:.1f} mm")
print(f"Isı kaybı: {Q:.2f} W/m")

# Boru sıcaklığı çok düşükse uyarı
if Tm < Ta - 10:
    print("\nUYARI: Boru sıcaklığı ortamdan çok düşük!")
    print("Pratikte, ısı kaybı ve donma riskini önlemek için daha kalın izolasyon gerekebilir.")
elif Tm > Ta:
    print("\nUYARI: Boru sıcaklığı ortamdan yüksek!")
    print("Yoğuşma riski yoktur. İzolasyon sadece ısı kaybını önlemek için kullanılabilir.")

pyinstaller --kondensat_hesabı.py