import time

print("Mauro entered the chat")
print("Mauro: Yo wsp guys")
time.sleep(3)
print("Pedo123: Yo wsp")
time.sleep(3)
print("KawaiiUwuSenoai: Haiii!!")
time.sleep(3)
print("Pedo123: How old are u fat nigga!!")
time.sleep(3)
print("KawaiiUwuSenpai: Im 13 teehee uwu")
time.sleep(3)
print("Pedo123: Uhh ur too old for meh *sighs*")
time.sleep(2) 
print("KawaiiUwuSenpai: NO NEVER I AM 7 I SWEAR!!!")
time.sleep(4)
print("Pedo123: Hmmm.. you sure? If your not i will be reporting you to the cp organization of Telegram officials")
time.sleep(4)
print("KawaiiUwuSenpai: Yes daddy ill send u so much cp while i cuck u in ur chasity cage (,,♡ᵕ♡,,)")
time.sleep(3)
print("Pedo123: Mauro, What do you think?")
fav_cunt = input("")
print(f"Mauro: {fav_cunt}")
time.sleep(3)
print("KawaiiUwuSenpai: Omg thx uwu")