from tkinter import *
application = Tk()

application.minsize(1500, 900)
application.geometry ("{}x{}+0+0". format(1920, 1080))
Label(application, text="Daily Tasks").grid(row=0, sticky=W)
var1 = IntVar()
Checkbutton(application, text="Finish all homework", variable=var1).grid(row=1, sticky=W)
var2 = IntVar()
Checkbutton(application, text="Train Memory for 30 mins", variable=var2).grid(row=2, sticky=W)
var3 = IntVar()
Checkbutton(application, text="cognitive training for 30 mins", variable=var3).grid(row=3, sticky=W)
var4 = IntVar()
Checkbutton(application, text="Learn a new skill", variable=var4).grid(row=4, sticky=W)
var5 = IntVar()
Checkbutton(application, text="take vitamin D", variable=var5).grid(row=5, sticky=W)
Button(application, text="Quit", command=application.quit ).grid(row=6, sticky=W, pady=4)
mainloop()
