print('|welecome to calculator app|'.title())
num1=float(input('1st number:'))
num2=float(input('2nd number:'))
print('__________________________')
print("Adding:"+str(num1+num2))
print('Subtract:'+str(num1-num2))
print('Multiply:'+str(num1*num2))
print('Divide:'+str(num1/num2))