def menu():
    print("██████╗ ██████╗ ███╗   ██╗███████╗████████╗     █████╗ ██╗")
print("██╔══██╗██╔══██╗████╗  ██║██╔════╝╚══██╔══╝    ██╔══██╗██║")
print("██║  ██║██║  ██║██╔██╗ ██║█████╗     ██║       ███████║██║")
print("██║  ██║██║  ██║██║╚██╗██║██╔══╝     ██║       ██╔══██║██║")
print("██████╔╝██████╔╝██║ ╚████║███████╗   ██║       ██║  ██║██║")
print("╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝   ╚═╝       ╚═╝  ╚═╝╚═╝")
print("")
print(" 1. Model          3. Model settings")
print(" 2. Settings      4. Start")

a = int(input("Choice: "))
if a == 1:
    print("1. Game-AI v2.3")
    print(" - 45K tokens/s ; 937h learn")
    print(" - 1,2GB ")
    print("")
    print("2. Free-AI 2 Premium")
    print(" - 31K tokens/s ; 553h learn")
    print(" - 937MB ")
    print("")
    print("3. Script+")
    print(" - 8K tokens/s ; only math")
    print(" - 2,5GB ")
    print("")
    print("4. Open-AI fast")
    print(" - 30K tokens/s ; 750h learn")
    print(" - 4,1GB ")
    print("")
    print("5. Back")
    b = input("Choice: ")

else:
    print("unknown")