# -*- coding: utf-8 -*-
"""DaThuNhanTu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YL4yYL1I_JVw9mM6MFBOTt_RR6NRNCf
"""



import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Khai báo biến
x, y, z = sp.symbols('x y z')

# Bước 1: Nhập đa thức
expr_str = input("Nhập đa thức (ví dụ: x^3 - 6*x^2 + 11*x - 6, hoặc x^2 + y^2 - 2*x*y): ")
expr = sp.sympify(expr_str)
print(f"✅ Đa thức nhập: {expr}")

# Bước 2: Phân tích nhân tử
factored = sp.factor(expr)
print(f"✅ Phân tích nhân tử: {factored}")

# Bước 3: Vẽ đồ thị
free_vars = list(expr.free_symbols)

if len(free_vars) == 1:
    # Đa thức 1 biến → vẽ 2D
    var = free_vars[0]
    f = sp.lambdify(var, expr, 'numpy')

    X = np.linspace(-10, 10, 400)
    Y = f(X)

    plt.figure(figsize=(6,4))
    plt.plot(X, Y, label=str(expr))
    plt.axhline(0, color="black", linewidth=0.8)
    plt.axvline(0, color="black", linewidth=0.8)
    plt.legend()
    plt.grid(True)
    plt.title("Đồ thị đa thức 1 biến")
    plt.show()

elif len(free_vars) == 2:
    # Đa thức 2 biến → vẽ 3D
    var1, var2 = free_vars
    f = sp.lambdify((var1, var2), expr, 'numpy')

    X = np.linspace(-5, 5, 100)
    Y = np.linspace(-5, 5, 100)
    X, Y = np.meshgrid(X, Y)
    Z = f(X, Y)

    fig = plt.figure(figsize=(7,5))
    ax = fig.add_subplot(111, projection="3d")
    ax.plot_surface(X, Y, Z, cmap="viridis", edgecolor="none")
    ax.set_title("Đồ thị 3D đa thức 2 biến")
    ax.set_xlabel(str(var1))
    ax.set_ylabel(str(var2))
    ax.set_zlabel("f(x,y)")
    plt.show()

else:
    print("⚠️ Chỉ hỗ trợ vẽ đa thức 1 hoặc 2 biến!")

