# -*- coding: utf-8 -*-
"""RAPORT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIfaliHeXQgc-0JdJWvsRy9Z43XgdrVm
"""

import pandas as pd

# Data pelajaran per jurusan
mapel_ipa = ["Matematika", "Fisika", "Kimia", "Biologi", "Bahasa Indonesia", "Bahasa Inggris", "Pendidikan Agama", "Pendidikan Pancasila"]
mapel_ips = ["Matematika", "Ekonomi", "Sosiologi", "Geografi", "Bahasa Indonesia", "Bahasa Inggris", "Pendidikan Agama", "Pendidikan Pancasila"]

# Fungsi predikat berdasarkan nilai rata-rata
def predikat(n):
    if n >= 90:
        return "A (Sangat Baik)"
    elif n >= 80:
        return "B (Baik)"
    elif n >= 70:
        return "C (Cukup)"
    elif n >= 60:
        return "D (Kurang)"
    else:
        return "E (Sangat Kurang)"

# Input data siswa dan nilai
daftar_siswa = [
    {
        "Nama Siswa": "Ali",
        "Kelas": "X IPA 1",
        "Jurusan": "IPA",
        "Nilai": {"Matematika": 85, "Fisika": 90, "Kimia": 78, "Biologi": 87, "Bahasa Indonesia": 88, "Bahasa Inggris": 82, "Pendidikan Agama": 92, "Pendidikan Pancasila": 90}
    },
    {
        "Nama Siswa": "Budi",
        "Kelas": "XI IPS 2",
        "Jurusan": "IPS",
        "Nilai": {"Matematika": 75, "Ekonomi": 80, "Sosiologi": 78, "Geografi": 72, "Bahasa Indonesia": 80, "Bahasa Inggris": 85, "Pendidikan Agama": 88, "Pendidikan Pancasila": 80}
    },
    {
        "Nama Siswa": "Citra",
        "Kelas": "XII IPA 1",
        "Jurusan": "IPA",
        "Nilai": {"Matematika": 92, "Fisika": 94, "Kimia": 88, "Biologi": 90, "Bahasa Indonesia": 84, "Bahasa Inggris": 89, "Pendidikan Agama": 95, "Pendidikan Pancasila": 91}
    },
]

# Proses data raport
rows = []
for siswa in daftar_siswa:
    # Pilih mapel sesuai jurusannya
    if siswa['Jurusan'] == 'IPA':
        mapel = mapel_ipa
    else:
        mapel = mapel_ips
    # Ambil nilai setiap mapel
    nilai_mapel = []
    for m in mapel:
        nilai = siswa['Nilai'].get(m, None)
        nilai_mapel.append(nilai)
    # Hitung rata-rata
    nilai_rata = sum([n for n in nilai_mapel if n is not None]) / len([n for n in nilai_mapel if n is not None])
    # Predikat
    pred = predikat(nilai_rata)
    # Buat satu baris raport
    row = {
        "Nama Siswa": siswa["Nama Siswa"],
        "Kelas": siswa["Kelas"],
        "Jurusan": siswa["Jurusan"],
        "Semester": "Ganjil",
        "Tahun Pelajaran": "2025-2026",
        "Rata-rata": round(nilai_rata, 2),
        "Predikat": pred,
    }
    # Tambahkan nilai tiap mapel
    for i, m in enumerate(mapel):
        row[m] = nilai_mapel[i]
    rows.append(row)

# Buat DataFrame raport
df = pd.DataFrame(rows)
# Tampilkan raport di terminal
print("RAPORT ONLINE SMA ISLAM AL GHOZALI\nTAHUN PELAJARAN 2025-2026 SEMESTER GANJIL\n")
print(df)

# Export ke Excel
df.to_excel("Raport_SMA_ISLAM_AL_GHOZALI_2025-2026_Semester_Ganjil.xlsx", index=False)
print("\nFile raport berhasil dibuat: 'Raport_SMA_ISLAM_AL_GHOZALI_2025-2026_Semester_Ganjil.xlsx'")