import pygame
import time


# Initialize Pygame and the mixer
pygame.mixer.pre_init(44100, -16, 2, 2048) # Optional: configure mixer before init
pygame.init()
print('I have a little suprise for you')
time.sleep(1.5)
print('I think you will like it')
time.sleep(0.5)
# Load and play background music
pygame.mixer.music.load("epic.wav")
pygame.mixer.music.play(-1) # Play infinitely
pygame.mixer.music.set_volume(0.5) # Set music volume
time.sleep(1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
print('RICK ROLL')
time.sleep(0.1)
