# -*- coding: utf-8 -*-
"""RR Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yn1IpjT3Ybl70v4UZBLlgPnyrhnm1u7C
"""

import pandas as pd
import re
import numpy as np
from google.colab import files

#spreadsheet url upload
url='https://docs.google.com/spreadsheets/d/1RDHx2ZkOfBkoB13PaG5mhGtGMQL_PGPd7E1QkCG2Cz8/export?format=csv'
companies = pd.read_csv(url)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

while True:
  print('To see all company names, enter "companies"\nTo see all company datapoints, enter "items"')
  print('To exit, enter "stop"')
  query = input("Enter a question: ")
  if query == 'companies':
    print(companies['Company Name'].to_string(index=False))
    continue
  elif query == 'items':
    items = companies.columns.tolist()
    for item in items:
      print(item)
    continue
  elif query == 'stop':
    break

  query = query.lower()
  queries = query.split()
  companies.set_index('Company Name', inplace=True)

  company_name = None
  attribute = None

  for company in companies.index:
    for q in queries:
      if q in company.lower():
        company_name = company
        break

  if company_name is None:
    print('Company not found.')
    continue

  for column in companies.columns:
    if q in column.lower():
      attribute = column
      break

  if attribute is None:
    print('Keyword not recognized.')
    continue

  output = companies.loc[company_name][attribute]
  if pd.isna(output):
    output = 'No current data.'

  print(output)