import time
import sysB


print('Hello Sarah Ji !!!!')
time.sleep(2)
print('My World')
time.sleep(1)
print('Meri Shona')
time.sleep(1)
print('Meri Khushi')
time.sleep(1)
print('Meri dua ki Jawab')
time.sleep(1)
print('Meri dil ki awaaz')
time.sleep(1)
print('Meri Jaan')
time.sleep(1)
print('So this is just to inform you that.......')
time.sleep(0.5)
print('.......')
time.sleep(0.5)
print('.......')
time.sleep(0.5)
print('.......')
time.sleep(0.5)
print('I LOVE YOU SOOOOO MUCH!!!!!!!!!!!')
time.sleep(2)
print('More than you know')
time.sleep(1)
print('More than you can imagine')
time.sleep(1)
print('More than you can understand')
time.sleep(1)
print('Umaaaaahhhhhhh')
time.sleep(1)
print('I hope Sarah Ji Also Loves Me So Much.....')
time.sleep(2)
print('You Love Me Right??????')
time.sleep(1)
print('Option A - You Love Me Sooooo Much !!!!!')
time.sleep(2)
print('Option B - You Just Love Me')
time.sleep(1)
ANSWER = input("your Choice Of Option Is : ")
time.sleep(1)

if ANSWER == "A":
    print('I love you soooo much tooooo jannnnuuuu!!!!!')
elif ANSWER == "B":
    print("I Still love you more meri jaaannnnuuuu!!!!!!!!")
else:
    print('Invalid input. Please Enter A or B')
time.sleep(2)
print('MUUUUUUAHHHHHHHHH!')
sys.exit()