print("Menghitung Luas Segitiga")
print()
print("Aplikasi ini dibuat dengan menggunakan python,")
print("dengan menggunakan sintax sederhana untuk menghitung")
print("Luas Segitiga umum dengan menggunankan rumus setengah alas x tinggi.")
print()
Tinggi=float(input("Masukkan tinggi segitiga = "))
Alas=float(input("masukkan Alas segitiga = "))
Luas=Tinggi*Alas/2
print("luas Segitiga = 1/2", Alas, "x", Tinggi, "= ", Luas,"Satuan Luas")
input()