# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyP2_2Qimr_lRw6b8vidc_6xFvZb6Sar
"""

# Jogo: Higiene das mãos para Técnico em Estética
# Autor: Andre
# Versão: 2.0

def main():
    print("=== Jogo: Higiene das Mãos ===")
    print("Siga corretamente os 20 passos da lavagem das mãos.\n")

    passos = [
        "Molhar as mãos com água corrente",
        "Aplicar sabão suficiente para cobrir todas as superfícies",
        "Esfregar palma contra palma",
        "Esfregar a palma direita sobre o dorso da mão esquerda e vice-versa",
        "Entrelaçar os dedos e esfregar",
        "Esfregar o dorso dos dedos contra a palma oposta",
        "Rotacionar o polegar direito na palma esquerda e vice-versa",
        "Rotacionar as pontas dos dedos na palma oposta",
        "Esfregar o pulso direito e depois o esquerdo",
        "Enxaguar bem as mãos com água corrente",
        "Secar as mãos com papel toalha descartável",
        "Usar papel toalha para fechar a torneira",
        "Evitar tocar superfícies sujas após lavar as mãos",
        "Lavar as mãos antes de atender o cliente",
        "Lavar as mãos após tocar superfícies contaminadas",
        "Lavar as mãos após usar o banheiro",
        "Lavar as mãos após tocar rosto ou cabelo",
        "Lavar as mãos antes de aplicar produtos estéticos",
        "Lavar as mãos após remover luvas descartáveis",
        "Aplicar álcool em gel quando necessário"
    ]

    pontos = 0

    print("Para cada passo, digite 'ok' quando achar que completou corretamente.\n")

    for i, passo in enumerate(passos, start=1):
        resposta = input(f"Passo {i}: {passo} - Digite 'ok' para confirmar: ").strip().lower()
        if resposta == "ok":
            pontos += 1
            print("✅ Passo registrado!\n")
        else:
            print("❌ Passo não confirmado.\n")

    print(f"Você completou o jogo! Pontuação final: {pontos}/20")

    if pontos == 20:
        print("🏆 Parabéns! Você domina todos os 20 passos da lavagem correta das mãos.")
    elif pontos >= 15:
        print("👍 Muito bem! Mas revise alguns passos importantes.")
    else:
        print("⚠️ Precisa estudar mais sobre a higiene das mãos!")

if __name__ == "__main__":
    main()
ok