# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQf0tqZtnsI6rmaf-AIvvdvfja9JYqX4
"""

import webbrowser
import time

score = 0

def ask(question, correct_answers):
    global score
    print("\n" + question)
    answer = input("> ").strip().lower()
    if answer in correct_answers:
        print("✅ Верно!")
        score += 1
    else:
        print("❌ Неверно...")
    time.sleep(1)

# 🎵 Фоновая музыка
print("🎵 Включаю фоновую музыку...")
webbrowser.open("https://youtu.be/KTPbW-4H_tk")
time.sleep(3)

print("\n👻 Добро пожаловать в жуткую викторину!\n")
time.sleep(1)

# ❓ Вопросы
ask("Сколько будет 6 + 7?", ["13"])
ask("Столица Японии?", ["токио"])
ask("Какой цвет получается при смешивании красного и синего?", ["фиолетовый"])

print(f"\nТы набрал {score} из 3 баллов.")
time.sleep(2)

# 😱 Последний вопрос
print("\nПоследний вопрос...")
time.sleep(1)
answer = input("Ты один в комнате? (да/нет): ").strip().lower()

if answer == "да":
    print("Ты уверен? Посмотри за спину.")
else:
    print("Значит, они уже рядом.")
time.sleep(2)

# 💀 Скример
print("\n⚠️ СИСТЕМА ОШИБКА: Обнаружено постороннее присутствие")
time.sleep(1)
print("!!!")
webbrowser.open("https://youtu.be/101aqh5WV3Q")
time.sleep(3)

# 🔐 Блокировка до ввода пароля
while True:
    password = input("\nВведите пароль для отключения скримера: ").strip()
    if password == "Nokia17092":
        print("🔓 Доступ разрешён. Скример отключён.")
        break
    else:
        print("🚫 Неверный пароль. Скример остаётся активным.")
        time.sleep(2)