import time
import random
import webbrowser

#"Loading" Sequence, currently noted for efficiency
print("Loading 'ZCRBLA v1.1.5'")
time.sleep(2)
print("Checking for updates.", end='\r')
time.sleep(1.6)
print("Checking for updates..", end='\r')
time.sleep(1.6)
print("Checking for updates...")
time.sleep(1.6)
print("Fully up to date!")
time.sleep(2)
print("Loading.", end='\r')
time.sleep(1)
print("Loading..", end='\r')
time.sleep(1)
print("Loading...")
time.sleep(1)
print("Starting.", end='\r')
time.sleep(2)
print("Starting..", end='\r')
time.sleep(2)
print("Starting...")
time.sleep(2)

#Variables 
#load - the base text used for "loading" the trivia game
load = "Loading Game"
#alli - the base text used to detect if "allison" is typed
alli = "alli"
#crtally - used to tally up how many trivia questions were answered correctly
crtally = 0
#wtally - used to tally up how many trivia questions were answered incorrectly
wtally = 0
#q1 - used to store any temporary information for the trivia game.
q1 = 0
#a1 - same as q1, but for the "alli" string of code
a1 = 'null'
#url - a rickroll :)
url = "https://www.youtube.com/watch?v=ALiLGgn3YGM&t=2s"

#First Input, all "elif" statments below are possible results, depending on what the user inputs
#Current (working) special inputs:
#zcrbla, ZCRBLA, load(followed by "skip" at the next input prompt), bob, Bob, david, David, davud, (starts with)kill, (starts with)Kill, loop, scan, porkandbeans, porkandbeans277, sportsguy89, exit, Buddy Holly, murder, Murder, (starts with)alli, liv, olivia. 
str = input("[Y/N]:" )
print("Scanning Text...")
time.sleep(2)
print("Analyzing...")
time.sleep(2)
#all below elif and if statments can be invoked by the "special" inputs listed above
if str.startswith("y") or str.startswith("Y") == True:
    print("Response Positive.")
    print("The input has", len(str),  "characters.")
    print("Here is the input displayed:", str)
elif str.startswith("n") or str.startswith("N") == True:
    print("Response Negative.")
    print("The input has", len(str), "characters.")
    print("Here is the input displayed:", str)
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == "zcrbla" or str == "ZCRBLA":
    print("Hey, how do you know my name? Also, that wasn't yes OR no.")
    print('You have 15 seconds before this tab closes.')    
    time.sleep(15)
elif str == "load":
    print('You should just stick to saying "yes" or "no", that is what this code is for.')
    for i in "Hey, get out of my code!":
        print(load + ".", end='\r')
        time.sleep(0.3)
        load = load + "."
    print("Loading Sequence attempted", len(load), "times.")
    gameStart = input('Loading Failed.  ')
    if gameStart == "re":
        print('Reloading...')
        time.sleep(2)
        print('Game Ready!')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('v')
        
        #Trivia Game :D
        print("Question One: What is the irrational fear that a duck is watching you at all times?")
        print("1. Anatidaephobia")
        print('2. Ailurophobia')
        print('3. Entomophobia')
        print('4. Arachnophobia')
        q1 = input("Answer Here(type the number of the answer you choose):")
        if q1 == "1":
            print("Yay, you did it! Feel free to take a break, or keep going!")
            crtally = crtally + 1
            time.sleep(1)
        else:
            print('Incorrect, better luck next time!(You can still continue)')
            wtally = wtally + 1
            time.sleep(1)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('v')
        print("Question Two: What is the third word in this sentence?")
        print('1. "Two"')
        print('2. ":"')
        print('3. "What"')
        print('4. "is"')
        q1 = input("Answer Here:")
        if q1 == "3":
            print("Yay, you did it! Go on to the next question!")
            crtally = crtally + 1
            time.sleep(1)
        else:
            print('Incorrect, better luck next time!(You can keep going)')
            wtally = wtally + 1
            time.sleep(1)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('v')
        print("Question Three:How many characters does the answer to number one have?")
        print("1.", len("Arachnophobia"))
        print('2.', len("Ailurophobia"))
        print('3.', len("Entomophobia"))
        print('4.', len("Anatidaephobia"))
        q1 = input("Answer Here:")
        if q1 == "4":
            print("Yay, you did it! Unfortunately, I'm too lazy to make anything else right now, but hey, you won! :D")
            crtally = crtally + 1
            time.sleep(1)
            print("For you--->", "🏆")
            time.sleep(1)
            print("Here are your statistics:")
            print("Amount answered Correctly:", crtally)
            print("Amount answered Incorrectly:", wtally)
            print('You have 15 seconds before this tab closes.')
            time.sleep(15)
        else:
            print('Well, that was the last question... and you got it wrong. No worries!! You can always just go back and do it agin, just run the code once more!')
            wtally = wtally + 1
            time.sleep(1)
            print("Here are your statistics:")
            print("Amount answered Correctly:", crtally)
            print("Amount answered Incorrectly:", wtally)
            print('You have 15 seconds before this tab closes.')
            time.sleep(15)
elif str == "bob" or str == "Bob":
    print("Bob... who is Bob??")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == "david" or str == "David":
    print('"Oh"')
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == "davud":
    print("you misspelled it.")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str.startswith('kill') == True or str.startswith('Kill') == True:
    print("Now, that just seems a bit TOO negative, doesn't it?")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == 'loop':
    while True:
        print("You Asked For This...")
elif str == 'scan':
    print('Commencing System Scan...')
    time.sleep(0.8)
    print('Scanning...')
    time.sleep(0.8)
    print('Scan Complete!')
    time.sleep(0.4)
    print("Scan Results: ZCRBLA is not working properly.")
    time.sleep(0.8)
    scan = input("Press 'Y' and then 'ENTER' to repair ZCRBLA, or press 'N' and then 'ENTER' to exit.")
    if scan == "Y":
        print("Scanning Target 'ZCRBLA' for issues...")
        time.sleep(0.4)
        print("Issue found: target 'ZCRBLA' has lost its marbles.")
        time.sleep(1)
        marble = input("Replace Marbles? [Y/N]")
        if marble == 'Y':
            print("Replacing...")
            time.sleep(0.6)
            print("Unable to complete request; target 'ZCRBLA' has too many issues.")
            print('You have 15 seconds before this tab closes.')
            time.sleep(15)
    if scan == 'N':
        print("Exiting...")
        time.sleep(0.6)
        print("Succesfully Exited.")
        print('You have 15 seconds before this tab closes.')
        time.sleep(15)
elif str == "porkandbeans":
    print("[Insert Weezer Riff]")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == "porkandbeans277":
    print("Username: PorkandBeans277")
    print("Password: *********")
    if input("View Password? [Y/N]: ") == "Y":
        print("You are a sick individual.")
        print('You have 15 seconds before this tab closes.')
        time.sleep(15)
    else:
        print("okay then.")
        print('You have 15 seconds before this tab closes.')
        time.sleep(15)
elif str == "sportsguy89":
    print("Check out this 'random' guy's channel -->")
    time.sleep(0.5)
    print("https://www.youtube.com/@Sportsguy89-d4i")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == "exit":
    print("Five minutes remaining.")
    time.sleep(60)
    print("Four minutes remaining.")
    time.sleep(60)
    print("Three minutes remaining.")
    time.sleep(60)
    print("Two minutes remaining.")
    time.sleep(60)
    print("One minute remaining.")
    time.sleep(60)
    print("3 Days till Mario steals your liver")
    time.sleep(3)
    exit()
elif str == "Buddy Holly":
    print("man i can't even escape this song in python code :pensive:")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str == "murder" or str == "Murder":
    print("hmm.... sounds fun, but i'm just some code, so i can't really help you :(.")
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)
elif str.startswith(alli) == True:
    print("Welcome Back, ")
    time.sleep(0.3)
    print("'", alli ,"'")
    time.sleep(1)
    print("What action would you like to take?")
    print('1. Change User Name')
    print('2. Play a game')
    print('3. Commit Tax Fraud')
    print('4. Suggest a new action')
    a1 = input('What would you like to do?(Type the number of the action you want)')
    if a1 == "1":
        print("Input New Name Below:")
        alli = input('--->')
        print('Registering.', end = '\r')
        time.sleep(0.3)
        print('Registering..', end = '\r')
        time.sleep(0.3)
        print('Registering...', end = '\r')
        time.sleep(0.3)
        print('Registration Complete!')
        time.sleep(0.2)
        print("New Name:", alli)
        print("Is that all?")
        a1 = input("[Y/N](uppercase): ")
        if a1 == 'Y':
            print("Good! Exiting Code...")
            time.sleep(4)
            exit()
        else:
            print('Sorry, that input is not recognized.')
            time.sleep(4)
            exit()
    elif a1 == "2":
        print('Reloading...')
        time.sleep(2)
        print('Game Ready!')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('v')
        
        #Trivia Game :D
        print("Question One: What is the irrational fear that a duck is watching you at all times?")
        print("1. Anatidaephobia")
        print('2. Ailurophobia')
        print('3. Entomophobia')
        print('4. Arachnophobia')
        q1 = input("Answer Here(type the number of the answer you choose):")
        if q1 == "1":
            print("Yay, you did it! Feel free to take a break, or keep going!")
            crtally = crtally + 1
            time.sleep(1)
        else:
            print('Incorrect, better luck next time!(You can still continue)')
            wtally = wtally + 1
            time.sleep(1)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('v')
        print("Question Two: What is the third word in this sentence?")
        print('1. "Two"')
        print('2. ":"')
        print('3. "What"')
        print('4. "is"')
        q1 = input("Answer Here:")
        if q1 == "3":
            print("Yay, you did it! Go on to the next question!")
            crtally = crtally + 1
            time.sleep(1)
        else:
            print('Incorrect, better luck next time!(You can keep going)')
            wtally = wtally + 1
            time.sleep(1)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('|')
        time.sleep(0.2)
        print('v')
        print("Question Three:How many characters does the answer to number one have?")
        print("1.", len("Arachnophobia"))
        print('2.', len("Ailurophobia"))
        print('3.', len("Entomophobia"))
        print('4.', len("Anatidaephobia"))
        q1 = input("Answer Here:")
        if q1 == "4":
            print("Yay, you did it! Unfortunately, I'm too lazy to make anything else right now, but hey, you won! :D")
            crtally = crtally + 1
            time.sleep(1)
            print("For you--->", "🏆")
            time.sleep(1)
            print("Here are your statistics:")
            print("Amount answered Correctly:", crtally)
            print("Amount answered Incorrectly:", wtally)
            print('You have 15 seconds before this tab closes.')
            time.sleep(15)
        else:
            print('Well, that was the last question... and you got it wrong. No worries!! You can always just go back and do it agin, just run the code once more!')
            wtally = wtally + 1
            time.sleep(1)
            print("Here are your statistics:")
            print("Amount answered Correctly:", crtally)
            print("Amount answered Incorrectly:", wtally)
            print('You have 15 seconds before this tab closes.')
            time.sleep(15)
    elif a1 == "3":
        print('Calling IRS...')
        time.sleep(3)
        print('IRS Contacted and notified of user\'s current location.')
        time.sleep(1)
        print('You have 3 minutes.')
        time.sleep(60)
        print('You have 2 minutes')
        time.sleep(60)
        print('You have 1 minute.')
        time.sleep(60)
        print('They are here.')
        time.sleep(5)
        exit()
    elif a1 == "4":
        print("Okay, type new action suggestion below:")
        input()
        print('Proccessing...')
        time.sleep(2)
        print('Suggestion sent!')
        print('You have 15 seconds before this tab closes.')
        time.sleep(15)
elif str == "liv" or str == "olivia":
    print('I haven\'t quite gotten around to this yet, so... ASCII OLIVE')
    time.sleep(5)
    print('                      ██▓▓██▓▓▒▒▒▒▒▒▓▓██████                      ')
    time.sleep(0.3)
    print('                ████▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓                ')    
    time.sleep(0.3)
    print('              ▓▓▒▒▒▒▒▒▓▓██▓▓▒▒▒▒▒▒▒▒▒▒▓▓▓▓██▓▓▒▒▒▒▓▓              ')    
    time.sleep(0.3)
    print('            ▓▓▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▓▓            ')    
    time.sleep(0.3)
    print('          ▓▓▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒▒▒▓▓          ')    
    time.sleep(0.3)
    print('        ██▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒▒▒██        ')    
    time.sleep(0.3)
    print('      ░░▒▒░░▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░      ')    
    time.sleep(0.3)
    print('      ▓▓▒▒░░░░▒▒▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▓▓      ')    
    time.sleep(0.3)
    print('    ▒▒▒▒░░░░▒▒▒▒▒▒▒▒▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    ')    
    time.sleep(0.3)
    print('    ▓▓▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓████▓▓▓▓████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓    ')    
    time.sleep(0.3)
    print('  ░░▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░  ')    
    time.sleep(0.3)
    print('  ▓▓▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓  ')    
    time.sleep(0.3)
    print('  ▓▓░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓  ')    
    time.sleep(0.3)
    print('  ▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ')    
    time.sleep(0.3)
    print('  ██▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██')    
    time.sleep(0.3)
    print(' ▓▓▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓')    
    time.sleep(0.3)
    print(' ██▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██')    
    time.sleep(0.3)
    print(' ▓▓░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓')    
    time.sleep(0.3)
    print(' ▓▓░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓')    
    time.sleep(0.3)
    print(' ▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')    
    time.sleep(0.3)
    print(' ▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')    
    time.sleep(0.3)
    print(' ▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')    
    time.sleep(0.3)
    print(' ██░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██')    
    time.sleep(0.3)
    print(' ██▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██')    
    time.sleep(0.3)
    print(' ▓▓▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓')    
    time.sleep(0.3)
    print(' ██▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██')    
    time.sleep(0.3)
    print('  ▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ')    
    time.sleep(0.3)
    print('  ██▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██  ')    
    time.sleep(0.3)
    print('  ██▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██  ')    
    time.sleep(0.3)
    print('    ▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    ')    
    time.sleep(0.3)
    print('    ▓▓▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓    ')    
    time.sleep(0.3)
    print('      ▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒      ')    
    time.sleep(0.3)
    print('      ██▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██      ')    
    time.sleep(0.3)
    print('        ▓▓▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓        ')    
    time.sleep(0.3)
    print('        ░░▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░        ')    
    time.sleep(0.3)
    print('          ▒▒▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒          ')    
    time.sleep(0.3)
    print('              ▓▓▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓            ')    
    time.sleep(0.3)
    print('               ▒▒▓▓▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒              ')    
    time.sleep(0.3)
    print('                  ▓▓▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓                  ')    
    time.sleep(0.3)
    print('                      ░░▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓░░                    ')    
    time.sleep(0.3)
    print('                              ████▓▓▓▓▓▓████                          ')    
    time.sleep(0.3)
    time.sleep(10)
    exit()
elif str == "machedrom" or str == "Machedrom":
    webbrowser.open("https://www.youtube.com/watch?v=ALiLGgn3YGM&t=2s")
else:
    print("You misspelled 'yes' or 'no'")
    print("The input has", len(str),  "characters.")
    print("Here is the input displayed:", str)
    print('You have 15 seconds before this tab closes.')
    time.sleep(15)