import random
import time
random_integer = random.randint(1, 1000)
print(f"случайное число: {random_integer}")
time.sleep(1)
print("грузим список")
time.sleep(0.1)
print("5%")
time.sleep(0.3)
print("10%")
time.sleep(0.8)
print("25%")
time.sleep(0.5)
print("35%")
time.sleep(0.5)
print("50%")
time.sleep(0.8)
print("70%")
time.sleep(0.5)
print("85%")
time.sleep(0.5)
print("100%")
time.sleep(0.1)
print("список загружен, ушло 6100 мс")
time.sleep(0.1)
# чет какой то список я честно хз что я понаписал тут
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
random.shuffle(my_list)
print(f"перемешанный список: {my_list}")