print(
    "Всю ответсвенность за DDDos атаки совершённые через програму пользователь берёт на себя!"
)
time.sleep(1)
print(".")
time.sleep(1)
print(".")
time.sleep(1)
print(".")
print("Вы уверены ? y/n")
a = input()
print("Введите адрес сайта")
b = input()
print("Адрес введён, ожидайте завершения процедуры атаки")
time.sleep(4)
print("Атака на сайт", b, "успешно завершена")
c = input()
