# -*- coding: utf-8 -*-
"""Софт.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLCuzoipJAOFRO0dAVly6pn3bSzcq_ez

https://t.me/joinchat/ScL1FOCgJCbFNJK1
https://t.me/joinchat/NfNPmjP3zcE2ZGI6
https://t.me/joinchat/lnadif8wefwqiHJB
https://t.me/joinchat/KAFNuak8fya9iawD
https://t.me/joinchat/MK86djdy97ddLJwD
https://t.me/joinchat/NfNPmjP3zcE2ZGI6
"""

links_list = input('Введите ссылки: ').split()
print()
print('Кол-во изначальных ссылок:', len(links_list))
print('Кол-во текущих ссылок:', len(set(links_list)))
for link in set(links_list):
  print(link)